/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kasclient

import (
	"encoding/json"
)

// DataPlaneClusterUpdateStatusRequestNodeInfo struct for DataPlaneClusterUpdateStatusRequestNodeInfo
type DataPlaneClusterUpdateStatusRequestNodeInfo struct {
	Ceiling                *int32 `json:"ceiling,omitempty"`
	Floor                  *int32 `json:"floor,omitempty"`
	Current                *int32 `json:"current,omitempty"`
	CurrentWorkLoadMinimum *int32 `json:"currentWorkLoadMinimum,omitempty"`
}

// NewDataPlaneClusterUpdateStatusRequestNodeInfo instantiates a new DataPlaneClusterUpdateStatusRequestNodeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPlaneClusterUpdateStatusRequestNodeInfo() *DataPlaneClusterUpdateStatusRequestNodeInfo {
	this := DataPlaneClusterUpdateStatusRequestNodeInfo{}
	return &this
}

// NewDataPlaneClusterUpdateStatusRequestNodeInfoWithDefaults instantiates a new DataPlaneClusterUpdateStatusRequestNodeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPlaneClusterUpdateStatusRequestNodeInfoWithDefaults() *DataPlaneClusterUpdateStatusRequestNodeInfo {
	this := DataPlaneClusterUpdateStatusRequestNodeInfo{}
	return &this
}

// GetCeiling returns the Ceiling field value if set, zero value otherwise.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetCeiling() int32 {
	if o == nil || o.Ceiling == nil {
		var ret int32
		return ret
	}
	return *o.Ceiling
}

// GetCeilingOk returns a tuple with the Ceiling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetCeilingOk() (*int32, bool) {
	if o == nil || o.Ceiling == nil {
		return nil, false
	}
	return o.Ceiling, true
}

// HasCeiling returns a boolean if a field has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) HasCeiling() bool {
	if o != nil && o.Ceiling != nil {
		return true
	}

	return false
}

// SetCeiling gets a reference to the given int32 and assigns it to the Ceiling field.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) SetCeiling(v int32) {
	o.Ceiling = &v
}

// GetFloor returns the Floor field value if set, zero value otherwise.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetFloor() int32 {
	if o == nil || o.Floor == nil {
		var ret int32
		return ret
	}
	return *o.Floor
}

// GetFloorOk returns a tuple with the Floor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetFloorOk() (*int32, bool) {
	if o == nil || o.Floor == nil {
		return nil, false
	}
	return o.Floor, true
}

// HasFloor returns a boolean if a field has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) HasFloor() bool {
	if o != nil && o.Floor != nil {
		return true
	}

	return false
}

// SetFloor gets a reference to the given int32 and assigns it to the Floor field.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) SetFloor(v int32) {
	o.Floor = &v
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetCurrent() int32 {
	if o == nil || o.Current == nil {
		var ret int32
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetCurrentOk() (*int32, bool) {
	if o == nil || o.Current == nil {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) HasCurrent() bool {
	if o != nil && o.Current != nil {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given int32 and assigns it to the Current field.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) SetCurrent(v int32) {
	o.Current = &v
}

// GetCurrentWorkLoadMinimum returns the CurrentWorkLoadMinimum field value if set, zero value otherwise.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetCurrentWorkLoadMinimum() int32 {
	if o == nil || o.CurrentWorkLoadMinimum == nil {
		var ret int32
		return ret
	}
	return *o.CurrentWorkLoadMinimum
}

// GetCurrentWorkLoadMinimumOk returns a tuple with the CurrentWorkLoadMinimum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) GetCurrentWorkLoadMinimumOk() (*int32, bool) {
	if o == nil || o.CurrentWorkLoadMinimum == nil {
		return nil, false
	}
	return o.CurrentWorkLoadMinimum, true
}

// HasCurrentWorkLoadMinimum returns a boolean if a field has been set.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) HasCurrentWorkLoadMinimum() bool {
	if o != nil && o.CurrentWorkLoadMinimum != nil {
		return true
	}

	return false
}

// SetCurrentWorkLoadMinimum gets a reference to the given int32 and assigns it to the CurrentWorkLoadMinimum field.
func (o *DataPlaneClusterUpdateStatusRequestNodeInfo) SetCurrentWorkLoadMinimum(v int32) {
	o.CurrentWorkLoadMinimum = &v
}

func (o DataPlaneClusterUpdateStatusRequestNodeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ceiling != nil {
		toSerialize["ceiling"] = o.Ceiling
	}
	if o.Floor != nil {
		toSerialize["floor"] = o.Floor
	}
	if o.Current != nil {
		toSerialize["current"] = o.Current
	}
	if o.CurrentWorkLoadMinimum != nil {
		toSerialize["currentWorkLoadMinimum"] = o.CurrentWorkLoadMinimum
	}
	return json.Marshal(toSerialize)
}

type NullableDataPlaneClusterUpdateStatusRequestNodeInfo struct {
	value *DataPlaneClusterUpdateStatusRequestNodeInfo
	isSet bool
}

func (v NullableDataPlaneClusterUpdateStatusRequestNodeInfo) Get() *DataPlaneClusterUpdateStatusRequestNodeInfo {
	return v.value
}

func (v *NullableDataPlaneClusterUpdateStatusRequestNodeInfo) Set(val *DataPlaneClusterUpdateStatusRequestNodeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPlaneClusterUpdateStatusRequestNodeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPlaneClusterUpdateStatusRequestNodeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPlaneClusterUpdateStatusRequestNodeInfo(val *DataPlaneClusterUpdateStatusRequestNodeInfo) *NullableDataPlaneClusterUpdateStatusRequestNodeInfo {
	return &NullableDataPlaneClusterUpdateStatusRequestNodeInfo{value: val, isSet: true}
}

func (v NullableDataPlaneClusterUpdateStatusRequestNodeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPlaneClusterUpdateStatusRequestNodeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
