/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kasclient

import (
	"encoding/json"
)

// DataPlaneClusterUpdateStatusRequestResizeInfo struct for DataPlaneClusterUpdateStatusRequestResizeInfo
type DataPlaneClusterUpdateStatusRequestResizeInfo struct {
	NodeDelta *int32                                              `json:"nodeDelta,omitempty"`
	Delta     *DataPlaneClusterUpdateStatusRequestResizeInfoDelta `json:"delta,omitempty"`
}

// NewDataPlaneClusterUpdateStatusRequestResizeInfo instantiates a new DataPlaneClusterUpdateStatusRequestResizeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPlaneClusterUpdateStatusRequestResizeInfo() *DataPlaneClusterUpdateStatusRequestResizeInfo {
	this := DataPlaneClusterUpdateStatusRequestResizeInfo{}
	return &this
}

// NewDataPlaneClusterUpdateStatusRequestResizeInfoWithDefaults instantiates a new DataPlaneClusterUpdateStatusRequestResizeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPlaneClusterUpdateStatusRequestResizeInfoWithDefaults() *DataPlaneClusterUpdateStatusRequestResizeInfo {
	this := DataPlaneClusterUpdateStatusRequestResizeInfo{}
	return &this
}

// GetNodeDelta returns the NodeDelta field value if set, zero value otherwise.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) GetNodeDelta() int32 {
	if o == nil || o.NodeDelta == nil {
		var ret int32
		return ret
	}
	return *o.NodeDelta
}

// GetNodeDeltaOk returns a tuple with the NodeDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) GetNodeDeltaOk() (*int32, bool) {
	if o == nil || o.NodeDelta == nil {
		return nil, false
	}
	return o.NodeDelta, true
}

// HasNodeDelta returns a boolean if a field has been set.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) HasNodeDelta() bool {
	if o != nil && o.NodeDelta != nil {
		return true
	}

	return false
}

// SetNodeDelta gets a reference to the given int32 and assigns it to the NodeDelta field.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) SetNodeDelta(v int32) {
	o.NodeDelta = &v
}

// GetDelta returns the Delta field value if set, zero value otherwise.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) GetDelta() DataPlaneClusterUpdateStatusRequestResizeInfoDelta {
	if o == nil || o.Delta == nil {
		var ret DataPlaneClusterUpdateStatusRequestResizeInfoDelta
		return ret
	}
	return *o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) GetDeltaOk() (*DataPlaneClusterUpdateStatusRequestResizeInfoDelta, bool) {
	if o == nil || o.Delta == nil {
		return nil, false
	}
	return o.Delta, true
}

// HasDelta returns a boolean if a field has been set.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) HasDelta() bool {
	if o != nil && o.Delta != nil {
		return true
	}

	return false
}

// SetDelta gets a reference to the given DataPlaneClusterUpdateStatusRequestResizeInfoDelta and assigns it to the Delta field.
func (o *DataPlaneClusterUpdateStatusRequestResizeInfo) SetDelta(v DataPlaneClusterUpdateStatusRequestResizeInfoDelta) {
	o.Delta = &v
}

func (o DataPlaneClusterUpdateStatusRequestResizeInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NodeDelta != nil {
		toSerialize["nodeDelta"] = o.NodeDelta
	}
	if o.Delta != nil {
		toSerialize["delta"] = o.Delta
	}
	return json.Marshal(toSerialize)
}

type NullableDataPlaneClusterUpdateStatusRequestResizeInfo struct {
	value *DataPlaneClusterUpdateStatusRequestResizeInfo
	isSet bool
}

func (v NullableDataPlaneClusterUpdateStatusRequestResizeInfo) Get() *DataPlaneClusterUpdateStatusRequestResizeInfo {
	return v.value
}

func (v *NullableDataPlaneClusterUpdateStatusRequestResizeInfo) Set(val *DataPlaneClusterUpdateStatusRequestResizeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPlaneClusterUpdateStatusRequestResizeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPlaneClusterUpdateStatusRequestResizeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPlaneClusterUpdateStatusRequestResizeInfo(val *DataPlaneClusterUpdateStatusRequestResizeInfo) *NullableDataPlaneClusterUpdateStatusRequestResizeInfo {
	return &NullableDataPlaneClusterUpdateStatusRequestResizeInfo{value: val, isSet: true}
}

func (v NullableDataPlaneClusterUpdateStatusRequestResizeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPlaneClusterUpdateStatusRequestResizeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
