ifdef::env-github,env-browser[:context: cmd]
[id='ref-context-status_{context}']
= context status

[role="_abstract"]
View the status of application services set in service context

[discrete]
== Synopsis

View the status of your application services. This command shows the status of each of your application services instances set in service context. 

To view the status of a specific application service, use "rhoas context status [service]".

Note: You can change the current instance for an application service with the "rhoas [service] use” command.


....
rhoas context status [args] [flags]
....

[discrete]
== Examples

....
# View the status of all application services in the current service context
$ rhoas context status

# View the status of all application services in a specific service context
$ rhoas context status --name dev

# View the status of the Kafka instance set in the current service context
$ rhoas context status kafka

# View the status of your services in JSON format
$ rhoas context status -o json

....

[discrete]
== Options

      `--name` _string_::       Name of the context
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-context_{context}[rhoas context]	 - Group, share and manage your rhoas services

