ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-topic-produce_{context}']
= kafka topic produce

[role="_abstract"]
Produce a new message to a topic

[discrete]
== Synopsis

Produce a message to a topic in a Kafka instance. Specify a file path for the CLI to read as the message value or use stdin to provide your message. You can specify the partition, key, and value.


....
rhoas kafka topic produce [flags]
....

[discrete]
== Examples

....
# Produce a single message to a topic from a file and provide a custom message key
$ rhoas kafka topic produce --name=users --file="./message.json" --key="{'location': 'us-east-1'}"

# Produce to a topic from standard input
$ rhoas kafka topic produce --name=users

# Produce to a topic from other command output
$ cat yourfile.json | rhoas kafka topic produce --name=users

# Produce to a topic and fetch its offset value
$ rhoas kafka topic produce --name=topic-1 --file="./message.json" | jq .offset

# Produce to a topic from a JSON file and filter using jq
$ cat input.json | jq .data.value | rhoas kafka topic produce --name=topic-1

# Produce to a topic and specified partition
$ rhoas kafka topic produce --name=topic-1 --file="./message.json" --partition=1

....

[discrete]
== Options

      `--file` _string_::          Path to file containing message value
      `--format` _string_::        Format for printing produced messages (possible values are "json" and "yaml") (default "json")
      `--instance-id` _string_::   Kafka instance ID. Uses the current instance if not set 
      `--key` _string_::           Message key. Empty if not set
      `--name` _string_::          Topic name
      `--partition` _int32_::      Partition number for the message. Must be a positive integer value that is valid for the specified topic

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list, and delete topics

