ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-namespace-list_{context}']
= connector namespace list

[role="_abstract"]
Get a list of Connectors namespaces

[discrete]
== Synopsis

Get a list of Connectors namespaces for the Connectors cluster. The "connector namespace list" command returns details about the namespaces including their ID values.


....
rhoas connector namespace list [flags]
....

[discrete]
== Examples

....
# Get a list of Connectors namespaces
rhoas connector namespace list

....

[discrete]
== Options

      `--limit` _int_::         Page limit (default 100)
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"
      `--page` _int_::          Page number (default 1)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector-namespace_{context}[rhoas connector namespace]	 - Connectors namespace commands

