ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-rule_{context}']
= service-registry rule

[role="_abstract"]
Manage artifact rules in a Service Registry instance

[discrete]
== Synopsis

Configure the validity and compatibility rules that govern artifact content.

When you add or update an artifact, Service Registry applies rules to check the validity and compatibility of the artifact content. Artifact rules apply to the specified artifact only. Global rules apply to all artifacts in a particular Service Registry instance. Configured artifact rules override any configured global rules. Before a new artifact version can be uploaded to the registry, all configured global rules or artifact rules must pass.

For more information about supported Service Registry content and rules, see https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817.


[discrete]
== Examples

....
## Enable the global compatibility rule for all artifacts in the current Service Registry instance
$ rhoas service-registry rule enable --rule-type=compatibility --config=full

## Enable the global compatibility rule for all artifacts in a specific Service Registry instance
$ rhoas service-registry rule enable --rule-type=compatibility --config=full-transitive --instance-id=8ecff228-1ffe-4cf5-b38b-55223885ee00

## Display the configuration details of the global validity rule for the current Service Registry instance
$ rhoas service-registry rule describe --rule-type=validity

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - Service Registry commands

 
* link:{path}#ref-service-registry-rule-describe_{context}[service-registry-rule describe]	 - Display the configuration details of a rule

 
* link:{path}#ref-service-registry-rule-disable_{context}[service-registry-rule disable]	 - Disable validity and compatibility rules

 
* link:{path}#ref-service-registry-rule-enable_{context}[service-registry-rule enable]	 - Enable validity and compatibility rules

 
* link:{path}#ref-service-registry-rule-list_{context}[service-registry-rule list]	 - List the validity and compatibility rules

 
* link:{path}#ref-service-registry-rule-update_{context}[service-registry-rule update]	 - Update the configuration of rules

