ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-rule-describe_{context}']
= service-registry rule describe

[role="_abstract"]
Display configuration of a rule

[discrete]
== Synopsis

View configuration details of compatibility or validity rule for the specified Service Registry instance or artifact.

....
rhoas service-registry rule describe [flags]
....

[discrete]
== Examples

....
## Display configuration details of global validity rule for current Service Registry instance
$ rhoas service-registry rule describe --rule-type=validity

## Display configuration details of compatibility rule for a specific artifact
$ rhoas service-registry rule describe --rule-type=compatibility --artifact-id=my-artifact --group=my-group

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
  `-o`, `--output` _string_::      Specify the output format. Choose from: "json", "yaml", "yml"
      `--rule-type` _string_::     Rule type determines how the content of an artifact can evolve over time

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-rule_{context}[rhoas service-registry rule]	 - Manage artifact rules in a Service Registry instance

