ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-update_{context}']
= kafka update

[role="_abstract"]
Update configuration details for a Kafka instance.

[discrete]
== Synopsis

Update configuration details for a Kafka instance. By modifying these settings, you can configure your Kafka instances to suit your particular environment.


....
rhoas kafka update [flags]
....

[discrete]
== Examples

....
# Update the Kafka instance owner
$ rhoas kafka update --name=my-kafka --owner=other-user

# Update the owner of the current Kafka instance
$ rhoas kafka update --owner=other-user

# Update the reauthentication configuration of the current Kafka instance
$ rhoas kafka update --reauthentication=true

# Update the current Kafka instance in interactive mode
$ rhoas kafka update

....

[discrete]
== Options

      `--id` _string_::                  Unique ID of the Kafka instance you want to update
      `--name` _string_::                Name of the Kafka instance you want to update
      `--owner` _string_::               ID of the user you want to set as the owner of this Kafka instance
      `--reauthentication` _Tribool_::   Enable or disable connection reauthentication for the Kafka instance
  `-y`, `--yes`::                        Skip confirmation of this action 

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances

