ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-role_{context}']
= service-registry role

[role="_abstract"]
Service Registry role management

[discrete]
== Synopsis


Manage Service Registry roles using a set of commands that give users one of following permissions:

* viewer (provides read access)
* manager (provides read and write access)
* admin (enables admin along with read and write access)

Roles can be applied to users (for example, "martin_redhat") and Service Account Client IDs (for example, "srvc-acct-03ddedba-5b49-4aa0-9b68-02e8b8c31add").
These commands are accessible only to users with the organization admin role or owners of the Service Registry instance.


[discrete]
== Examples

....
## Create or update user role
rhoas service-registry role add --role=admin --username=joedough

## List user and service account roles
rhoas service-registry role list

## Revoke role for user
rhoas service-registry role revoke --username=janedough

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - Service Registry commands

 
* link:{path}#ref-service-registry-role-add_{context}[service-registry-role add]	 - Add or update principal role

 
* link:{path}#ref-service-registry-role-list_{context}[service-registry-role list]	 - List roles

 
* link:{path}#ref-service-registry-role-revoke_{context}[service-registry-role revoke]	 - Revoke role for principal

