ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-cluster-update_{context}']
= connector cluster update

[role="_abstract"]
Update a Connectors cluster

[discrete]
== Synopsis

Update a Connectors cluster

....
rhoas connector cluster update [flags]
....

[discrete]
== Examples

....
# Update name of a connector cluster
rhoas connector cluster update --id cdh0s0bjdpqd9bgomcbg --name my-connector

# Update annotations of a connector cluster
rhoas connector cluster update --id cdh0s0bjdpqd9bgomcbg --annotations h1=head

....

[discrete]
== Options

      `--annotations` _key=value_::   comma-separated list of string annotations in key=value format
      `--id` _string_::               ID of the Connectors cluster to update
      `--name` _string_::             Name of the Connectors cluster

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector-cluster_{context}[rhoas connector cluster]	 - Create, delete, and list Connectors clusters

