ifdef::env-github,env-browser[:context: cmd]
[id='ref-completion_{context}']
= completion

[role="_abstract"]
Install command completion for your shell (bash, zsh, or fish)

[discrete]
== Synopsis

Install rhoas command completion for your shell (bash, zsh, or fish).

To find what shell you are currently running:

  $ echo $0

For instructions on installing command completions for your shell:

  $ rhoas completion [bash|zsh|fish] -h

When you have installed the command completion script, restart your shell for the changes to take effect.


[discrete]
== Examples

....
## Generate command completion script for Bash shell
rhoas completion bash

## Generate command completion script for fish shell
rhoas completion fish

## Generate command completion script for Zsh shell
rhoas completion zsh

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI

 
* link:{path}#ref-completion-bash_{context}[completion bash]	 - Generate command completion script for Bash shell

 
* link:{path}#ref-completion-fish_{context}[completion fish]	 - Generate command completion script for fish shell

 
* link:{path}#ref-completion-zsh_{context}[completion zsh]	 - Generate command completion script for Zsh shell

