ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-role-list_{context}']
= rhoas service-registry role list

[role="_abstract"]
[alpha] List roles

[discrete]
== Synopsis

Listing all roles on selected instance
This command is available as part of the Development Preview release.


....
rhoas service-registry role list [flags]
....

[discrete]
== Examples

....
## List user and service account roles
rhoas service-registry role list

....

[discrete]
== Options

      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
  `-o`, `--output` _string_::      Output format (json, yaml, yml)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_role.adoc#rhoas-service-registry-role[rhoas service-registry role]	 - [alpha] Service Registry role management
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-role_{context}[rhoas service-registry role]	 - [alpha] Service Registry role management
endif::[]

