ifdef::env-github,env-browser[:context: cmd]
[id='ref-dedicated-register-cluster_{context}']
= dedicated register-cluster

[role="_abstract"]
Register an OpenShift cluster with Red Hat OpenShift Streams for Apache Kafka

[discrete]
== Synopsis

You can use your own OpenShift cluster to provision your kafkas which will be managed by Red Hat Streams for Apache Kafka.
This command will register your cluster with Red Hat Streams for Apache Kafka.


....
rhoas dedicated register-cluster [flags]
....

[discrete]
== Examples

....
# Register an OpenShift cluster with Red Hat Streams for Apache Kafka by selecting from a list of available clusters.
rhoas cluster register-cluster

# Register an OpenShift cluster with Red Hat Streams for Apache Kafka by specifying the cluster ID.
rhoas cluster register-cluster --cluster-id 1234-5678-90ab-cdef

....

[discrete]
== Options

      `--access-token` _string_::           The access token to use to authenticate with the OpenShift Cluster Management API.
      `--cluster-id` _string_::             The ID of the OpenShift cluster to register:
      `--cluster-mgmt-api-url` _string_::   The API URL of the OpenShift Cluster Management API.

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-dedicated_{context}[rhoas dedicated]	 - Manage your OpenShift clusters which host your kafkas.

