ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact-export_{context}']
= service-registry artifact export

[role="_abstract"]
Export data from Service Registry instance

[discrete]
== Synopsis

Export all artifacts and metadata from a Service Registry instance to a specified file


....
rhoas service-registry artifact export [flags]
....

[discrete]
== Examples

....
## Export all artifacts and metadata to export file for another Service Registry instance
rhoas service-registry artifact export --output-file=export.zip

....

[discrete]
== Options

      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--output-file` _string_::   File location of the artifact

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts

