ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector_{context}']
= connector

[role="_abstract"]
Connectors commands

[discrete]
== Synopsis

With Red Hat OpenShift Connectors, you can create and configure connections between Red Hat OpenShift Streams for Apache Kafka and third-party systems. You can configure Connectors that retrieve data (data source Connectors) and Connectors that specify where to send data (data sink Connectors).

To get started:
1. Decide which type of connector you want to create.
   Use the "rhoas connector type list" command to see a list of connector types
2. Build a configuration file based on one of the connector types.
   Use the "rhoas connector build" command to build a configuration file.
3. Optionally, edit the configuration file.
   Use a text editor of your choice to edit the configuration file.
4. Create a Connectors instance by specfiying the configuration file.
   Use the "rhoas connector create" command to create a Connectors instance.
5. Start the Connectors instance by using the "rhoas connector start" command.
6. Stop the Connectors instance by using the "rhoas connector stop" command.


[discrete]
== Examples

....
   
# List all connector types
rhoas connector type list

# Build a Connectors configuration file named "my_aws_lambda_connector.json" that is based on the "aws_lambda_sink_0.1" connector type
rhoas connector build --name=my_aws_lambda_connector --type=--type=aws_lambda_sink_0.1

# Create a Connectors instance by specifying a configuration file
rhoas connector create --file=myconnector.json

# Update an existing Connectors instance by specifying a configuration file
rhoas connector update --id=my-connector --file=myconnector.json

# List of Connectors instances
rhoas connector list

# Start the Connectors instance with ID my-connector
rhoas connector start --id=my-connector

# Stop the current Connectors instance
rhoas connector stop

# Delete a Connectors instance with ID my-connector
rhoas connector delete --id=my-connector

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI

 
* link:{path}#ref-connector-build_{context}[connector build]	 - Build a Connectors instance

 
* link:{path}#ref-connector-cluster_{context}[connector cluster]	 - Create, delete, and list Connectors clusters

 
* link:{path}#ref-connector-create_{context}[connector create]	 - Create a Connectors instance

 
* link:{path}#ref-connector-delete_{context}[connector delete]	 - Delete a Connectors instance

 
* link:{path}#ref-connector-describe_{context}[connector describe]	 - Get the details for the Connectors instance

 
* link:{path}#ref-connector-list_{context}[connector list]	 - List of Connectors instances

 
* link:{path}#ref-connector-namespace_{context}[connector namespace]	 - Connectors namespace commands

 
* link:{path}#ref-connector-start_{context}[connector start]	 - Start a Connectors instance

 
* link:{path}#ref-connector-stop_{context}[connector stop]	 - Stop a Connectors instance

 
* link:{path}#ref-connector-type_{context}[connector type]	 - List and get details of the different connector types

 
* link:{path}#ref-connector-update_{context}[connector update]	 - Update a Connectors instance

 
* link:{path}#ref-connector-use_{context}[connector use]	 - Set the current Connectors instance

