ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-topic-create_{context}']
= kafka topic create

[role="_abstract"]
Create a topic

[discrete]
== Synopsis

Create a topic in the current Kafka instance. You can specify the cleanup policy, number of partitions, retention size, and retention time.

The replicas are preconfigured. The number of partition replicas for the topic is set to 3 and the minimum number of follower replicas that must be in sync with a partition leader is set to 2.


....
rhoas kafka topic create [flags]
....

[discrete]
== Examples

....
# Create a topic
$ rhoas kafka topic create --name topic-1

....

[discrete]
== Options

      `--cleanup-policy` _string_::   Determines whether log messages are deleted, compacted, or both (default "delete")
      `--instance-id` _string_::      Kafka instance ID. Uses the current instance if not set 
      `--name` _string_::             Topic name
  `-o`, `--output` _string_::         Specify the output format. Choose from: "json", "yaml", "yml"
      `--partitions` _int32_::        The number of partitions in the topic (default 1)
      `--retention-bytes` _int_::     The maximum total size of a partition log segments before old log segments are deleted to free up space.
Value of -1 is set by default indicating no retention size limits (default -1)
      `--retention-ms` _int_::        The period of time in milliseconds the broker will retain a partition log before deleting it (default 604800000)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list, and delete topics

