ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-account-list_{context}']
= service-account list

[role="_abstract"]
List all service accounts

[discrete]
== Synopsis

List all service accounts.

This command provides a high-level view of all service accounts.

The service accounts are displayed by default in a table, but can also be displayed in JSON or YAML format.


....
rhoas service-account list [flags]
....

[discrete]
== Examples

....
# List all service accounts using the default output format
$ rhoas service-account list

# List all service accounts using JSON as the output format
$ rhoas service-account list -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the service accounts (choose from: "json", "yml", "yaml")
      `--page` _int32_::        Current page number for the list (default 1)
      `--size` _int32_::        Maximum number of items to be returned per page (default 100)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete, and update service accounts

