ifdef::env-github,env-browser[:context: cmd]
[id='ref-context-set-connector_{context}']
= context set-connector

[role="_abstract"]
Set the current Connectors instance

[discrete]
== Synopsis

Set a Connectors instance as the current instance. The rhoas CLI uses the 
current Connectors instance when you run any rhoas connector cluster commands.

You can set a Connectors instance as the current instance by providing its name or ID.


....
rhoas context set-connector [flags]
....

[discrete]
== Examples

....
# Set the current Connectors instance by providing the name of a Connectors instance
$ rhoas context set-connector --name=my-connector

# Set the current Connectors instance by providing the ID of a Connectors instance
$ rhoas context set-connector --id=1iSSK8RQ3JKI8Q0OTFHF5FRg

....

[discrete]
== Options

      `--id` _string_::     The unique ID of the Connectors instance that you want to set as the current instance
      `--name` _string_::   The name of the Connectors instance that you want to set as the current instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-context_{context}[rhoas context]	 - Group, share and manage your rhoas services

