ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-consumer-group-describe_{context}']
= rhoas kafka consumer-group describe

[role="_abstract"]
Describe a consumer group

[discrete]
== Synopsis

Print detailed information for a consumer group and its members.


....
rhoas kafka consumer-group describe [flags]
....

[discrete]
== Examples

....
# describe a consumer group
$ rhoas kafka consumer-group describe --id consumer_group_1 -o json

....

[discrete]
== Options

      `--id` _string_::         The unique ID of the consumer group to view
  `-o`, `--output` _string_::   Format in which to display the consumer group. Choose from: "json", "yml", "yaml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_consumer-group.adoc#rhoas-kafka-consumer-group[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance.
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-consumer-group_{context}[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance.
endif::[]

