ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-role-add_{context}']
= service-registry role add

[role="_abstract"]
Add or update principal role

[discrete]
== Synopsis


Add or update one of the following roles for a user or service account:

* viewer (provides read access)
* manager (provides read and write access)
* admin (provides admin access as well as read and write access)


....
rhoas service-registry role add [flags]
....

[discrete]
== Examples

....
## Create or update user role
rhoas service-registry role add --role=admin --username=joedough

....

[discrete]
== Options

      `--instance-id` _string_::       ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--role` _string_::              Role to apply: admin, manager, or viewer
      `--service-account` _string_::   ServiceAccount name
      `--username` _string_::          Username of the user within organization

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-role_{context}[rhoas service-registry role]	 - Service Registry role management

