ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-type_{context}']
= connector type

[role="_abstract"]
List and get details of the different connector types

[discrete]
== Synopsis

List and get details of connector types that are available in the connector catalog. 

To see a list of all available connector types, use the "type list" command.
You can optionally use the "--search" flag to filter the requested results by Connector types that start with or contain text that you specify. 

To see a description of a specific connector type, use the "type details" command.


[discrete]
== Examples

....
# List all connector types
rhoas connector type list

# List all connector types that start with "Amazon"
rhoas connector type list --search=Amazon%

# Get all of the details for the connector type by specifying the type ID
rhoas connector type describe --type=aws_kinesis_sink_0.1

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector_{context}[rhoas connector]	 - Connectors commands

 
* link:{path}#ref-connector-type-describe_{context}[connector-type describe]	 - Get details of a connector type

 
* link:{path}#ref-connector-type-list_{context}[connector-type list]	 - List connector types

