ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-rule-disable_{context}']
= service-registry rule disable

[role="_abstract"]
Disable validity and compatibility rules

[discrete]
== Synopsis

Disable validity and compatibility rules for the specified Service Registry instance or artifact

....
rhoas service-registry rule disable [flags]
....

[discrete]
== Examples

....
## Disable global compatibility rule for artifacts of the current Service Registry instance
$ rhoas service-registry rule disable --rule-type=compatibility

## Disable global compatibility rule for artifacts of a specific Service Registry instance
$ rhoas service-registry rule disable --rule-type=compatibility --instance-id 8ecff228-1ffe-4cf5-b38b-55223885ee00

## Disable validity rule for a specific artifact
$ rhoas service-registry rule disable --rule-type=validity --artifact-id=my-artifact

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--rule-type` _string_::     Rule type determines how the content of an artifact can evolve over time
  `-y`, `--yes`::                  Disable rule(s) without prompt

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-rule_{context}[rhoas service-registry rule]	 - Manage artifact rules in a Service Registry instance

