ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-cluster-delete_{context}']
= connector cluster delete

[role="_abstract"]
Delete a Connectors cluster

[discrete]
== Synopsis

Delete a Connectors cluster by specifying its cluster ID. To see a list of all Connectors clusters and their ID values, use the "connector cluster list" command.


....
rhoas connector cluster delete [flags]
....

[discrete]
== Examples

....
# Delete a Connectors cluster that has ID c980124otd37bufiemj0
rhoas connector cluster delete --id=c980124otd37bufiemj0

....

[discrete]
== Options

      `--id` _string_::         ID of the Connectors cluster to delete
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"
  `-y`, `--yes`::               Skip confirmation of this action 

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector-cluster_{context}[rhoas connector cluster]	 - Create, delete, and list Connectors clusters

