ifdef::env-github,env-browser[:context: cmd]
[id='ref-generate-config_{context}']
= generate-config

[role="_abstract"]
Generate configurations for the service context

[discrete]
== Synopsis

Generate configuration files for the service context to connect with to be used with various tools and platforms

You must specify an output format into which the credentials will be stored:

- env (default): Store configurations in an env file as environment variables
- json: Store configurations in a JSON file
- properties: Store configurations in a properties file, which is typically used in Java-related technologies
- secret: Store configurations in a Kubernetes secret file


....
rhoas generate-config [flags]
....

[discrete]
== Examples

....
## Generate configurations for the current service context in json format
$ rhoas generate-config --type json

## Generate configurations for the current service context in env format and save it in specified path
$ rhoas generate-config --type env --output-file ./configs/.env

## Generate configurations for a specified context as Kubernetes secret
$ rhoas generate-config --name qaprod --type secret

....

[discrete]
== Options

      `--name` _string_::          Name of the context
      `--output-file` _string_::   Sets a custom file location to save the configurations
      `--overwrite`::              Forcibly overwrite a configuration file if it already exists
      `--type` _string_::          Type of configuration file to be generated

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI

