ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-login_{context}']
= rhoas login

[role="_abstract"]
Log in to RHOAS

[discrete]
== Synopsis

Log in securely to RHOAS through a web browser.

This command opens your web browser, where you can enter your credentials.

When using the rhoas CLI in an environment without a web browser, 
you can log in using an offline-token by passing the "--token" flag, which can be obtained at https://console.redhat.com/openshift/token.
Note: token-based login is not supported by the Kafka "topic" and "consumer-group" subcommands.


....
rhoas login [flags]
....

[discrete]
== Examples

....
# securely log in to RHOAS by using a web browser
$ rhoas login

# print the authentication URL instead of automatically opening the browser
$ rhoas login --print-sso-url

# log in using an offline token
$ rhoas login --token <your-token>

....

[discrete]
== Options

      `--api-gateway` _string_::    URL of the API gateway. (default "https://api.openshift.com")
      `--auth-url` _string_::       The URL of the SSO Authentication server. (default "https://sso.redhat.com/auth/realms/redhat-external")
      `--client-id` _string_::      OpenID client identifier (default "rhoas-cli-prod")
      `--insecure`::                Enables insecure communication with the server. This disables verification of TLS certificates and host names.
      `--mas-auth-url` _string_::   The URL of the identity.api.openshift.com Authentication server. (default "https://identity.api.openshift.com/auth/realms/rhoas")
      `--print-sso-url`::           Prints the console login URL, which you can use to log in to RHOAS from a different web browser. This is useful if you need to log in with different credentials than the credentials you used in your default web browser.
      `--scope` _stringArray_::     Override the default OpenID scope. To specify multiple scopes, use a separate --scope for each scope. (default [openid])
  `-t`, `--token` _string_::        Allows you to log in using an offline token, which can be obtained at https://console.redhat.com/openshift/token.

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas.adoc#rhoas[rhoas]	 - RHOAS CLI
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI
endif::[]

