ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact-update_{context}']
= service-registry artifact update

[role="_abstract"]
Update artifact

[discrete]
== Synopsis

Update an artifact from a file or directly from standard input.

Artifacts are typically in JSON format for most supported types, but might be in another format for some types (for example, PROTOBUF).
The type of the content should be compatible with the current artifact type.

When successful, this command creates a new version of the artifact, making it the most recent (and therefore official) version of the artifact.

An artifact is updated using the content provided in the request body.
This content is updated under a unique artifactId provided by the user.

Updated artifact content should conform to the validity and compatibility rules set for the registry instance.


....
rhoas service-registry artifact update [flags]
....

[discrete]
== Examples

....
## update artifact from group and artifact-id
rhoas service-registry artifact update --artifact-id=my-artifact --group my-group my-artifact.json

## update artifact from group and artifact-id
rhoas service-registry artifact update --artifact-id=my-artifact --group my-group my-artifact.json

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
      `--description` _string_::   Custom description of the artifact
  `-f`, `--file` _string_::        File location of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--name` _string_::          Custom name of the artifact
      `--version` _string_::       Custom version of the artifact (for example 1.0.0)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts

