ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-type_{context}']
= connector type

[role="_abstract"]
List and get details of different connector types

[discrete]
== Synopsis

List, search and get details of connector types that are available to use in the connector catalog.

Use list to list available connector types.

Use describe to get more details about a specific connector type.


[discrete]
== Examples

....
# List all connector types
rhoas connector type list

# List all connector types that start with 'Amazon'
rhoas connector type list --search=Amazon%

# Get more details of connector type with a type id of IEJF87hg2342hsdHFG
rhoas connector type describe --id=IEJF87hg2342hsdHFG

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector_{context}[rhoas connector]	 - Connectors instance commands

 
* link:{path}#ref-connector-type-list_{context}[connector-type list]	 - List connector types

