ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact-delete_{context}']
= service-registry artifact delete

[role="_abstract"]
Deletes an artifact or all artifacts in a given group

[discrete]
== Synopsis

Deletes a single artifact or all artifacts in a given group:

* When called without arguments, deletes all artifacts in the group.
* When --artifact-id is specified, deletes only a single artifact and its version.
* When --group is omitted, the command uses the "default" group.


....
rhoas service-registry artifact delete [flags]
....

[discrete]
== Examples

....
## Delete all artifacts in the group "default"
rhoas service-registry artifact delete

## Delete artifact in the group "default" with name "my-artifact"
rhoas service-registry artifact delete --artifact-id=my-artifact

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
  `-y`, `--yes`::                  Delete artifact without prompt

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts

