ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-setting-list_{context}']
= service-registry setting list

[role="_abstract"]
List settings for a Service Registry instance

[discrete]
== Synopsis

List all settings for a Service Registry instance with their values and types

....
rhoas service-registry setting list [flags]
....

[discrete]
== Examples

....
## List all settings for the current Service Registry instance
$ rhoas service-registry setting list

## List all settings for a specific Service Registry instance
$ rhoas service-registry setting list --instance-id=8ecff228-1ffe-4cf5-b38b-55223885ee00

....

[discrete]
== Options

      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-setting_{context}[rhoas service-registry setting]	 - Configure settings for a Service Registry instance

