ifdef::env-github,env-browser[:context: cmd]
= [[ref-rhoas-config-dev-preview_{context}]]rhoas config dev-preview

[role="_abstract"]
Sets development preview features in config

[discrete]
== Synopsis

Dev preview is used to enable commands in the CLI that are not available for general use. 
Those commands usually work against alpha versions of the API and might often have breaking changes.


....
rhoas config dev-preview [flags]
....

[discrete]
== Examples

....
# change dev preview configuration
$ rhoas config dev-preview true

....

[discrete]
== Options inherited from parent commands

  `-d`, `--debug`::   Enable debug mode
  `-h`, `--help`::    Show help for a command

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_config.adoc#user-content-ref-rhoas-config_{context}[rhoas config]	 - Change specific configuration for the options
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-config_{context}[rhoas config]	 - Change specific configuration for the options
endif::[]

