ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-setting-get_{context}']
= service-registry setting get

[role="_abstract"]
Get value of the setting for a Service Registry instance

[discrete]
== Synopsis

Get the formatted value of the setting and other information for a Service Registry instance

....
rhoas service-registry setting get [flags]
....

[discrete]
== Examples

....
## Get the setting for a Service Registry instance by name
$ rhoas service-registry setting get --name registry.ccompat.legacy-id-mode.enabled

## Get the setting for a Service Registry instance in YAML format by name
$ rhoas service-registry setting get --name registry.ccompat.legacy-id-mode.enabled --output yaml

....

[discrete]
== Options

      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
  `-n`, `--name` _string_::        Name of the setting for a Service Registry instance
  `-o`, `--output` _string_::      Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-setting_{context}[rhoas service-registry setting]	 - Configure settings for a Service Registry instance

