ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-rule-list_{context}']
= service-registry rule list

[role="_abstract"]
List the validity and compatibility rules

[discrete]
== Synopsis

List the validity and compatibility rules for the specified Service Registry instance or artifact.

....
rhoas service-registry rule list [flags]
....

[discrete]
== Examples

....
## List the global rules for all artifacts in the current Service Registry instance
$ rhoas service-registry rule list

## List the global rules for all artifacts in a specific Service Registry instance
$ rhoas service-registry rule list --instance-id=8ecff228-1ffe-4cf5-b38b-55223885ee00

## List the artifact rules for a specific artifact
$ rhoas service-registry rule list --artifact-id=my-artifact

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-rule_{context}[rhoas service-registry rule]	 - Manage artifact rules in a Service Registry instance

