ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-use_{context}']
= rhoas kafka use

[role="_abstract"]
Set the current Apache Kafka instance

[discrete]
== Synopsis

Select an Apache Kafka instance and set it as the current instance.
You can specify a Apache Kafka instance by --name or --id.

When you set the Kafka instance to be used, it is set as the current instance for all rhoas kafka topics and rhoas kafka consumer-group commands.



....
rhoas kafka use [flags]
....

[discrete]
== Examples

....
# set a kafka instance to be the current instance
$ rhoas kafka use --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg,

....

[discrete]
== Options

      `--id` _string_::     Unique ID of the Kafka instance you want to set as the current instance
      `--name` _string_::   Name of the Kafka instance you want to set as the current instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka.adoc#rhoas-kafka[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]

