ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-update_{context}']
= connector update

[role="_abstract"]
Update a Connectors instance

[discrete]
== Synopsis

Update a Connectors instance.

You can change the details of an existing Connectors instance by changing its configuration in a text editor. To specify an editor, use the EDITOR environment variable before you run the "rhoas connector update" command. For example:

export EDITOR=nvim
export EDITOR=vim
export EDITOR="code -w"


....
rhoas connector update [flags]
....

[discrete]
== Examples

....
# Update a Connectors instance
rhoas connector update --id=my-connector --file=myconnector.json

# Update a Connectors instance from stdin
cat myconnector.json | rhoas connector update

....

[discrete]
== Options

      `--kafka-id` _string_::       ID of the namespace in which you want to deploy the Connectors instance
      `--name` _string_::           Override the name of the Connectors instance (the default name is the name specified in the connector configuration file)
      `--namespace-id` _string_::   ID of of the Kafka instance that you want the Connectors instance to use
  `-o`, `--output` _string_::       Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector_{context}[rhoas connector]	 - Connectors commands

