ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact-list_{context}']
= service-registry artifact list

[role="_abstract"]
List artifacts

[discrete]
== Synopsis

List all artifacts for the group in the specified output format (by default, "table")

....
rhoas service-registry artifact list [flags]
....

[discrete]
== Examples

....
## List all artifacts for the "default" artifact group
rhoas service-registry artifact list

## List all artifacts in all groups
rhoas service-registry artifact list --all-groups

## List all artifacts with "my-group" group
rhoas service-registry artifact list --group=my-group

## List all artifacts with limit and group
rhoas service-registry artifact list --page=2 --limit=10

## List all artifacts for the "default" artifact group with name containing "sample"
rhoas service-registry artifact list --name sample

## List all artifacts for the "default" artifact group having labels "my-label" and "sample"
rhoas service-registry artifact list --label "my-label" --labels "sample"

## List all artifacts for the "default" artifact group with description containing "sample"
rhoas service-registry artifact list --description sample

....

[discrete]
== Options

  `-a`, `--all-groups`::             List artifacts in all groups
      `--description` _string_::     Text search to filter artifacts by description
  `-g`, `--group` _string_::         Artifact group (default "default")
      `--instance-id` _string_::     ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--label` _stringArray_::      Text search to filter artifacts by labels
      `--limit` _int32_::            Page limit (default 100)
      `--name` _string_::            Text search to filter artifacts by name
  `-o`, `--output` _string_::        Output format (json, yaml, yml)
      `--page` _int32_::             Page number (default 1)
      `--property` _stringArray_::   Text search to filter artifacts by properties (separate each name/value pair using a colon)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts

