ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-build_{context}']
= connector build

[role="_abstract"]
Build a Connectors instance

[discrete]
== Synopsis

Build a configuration file by specifying a connector type.
For a list of available connector types, use the "connector type list" command.

The "connector build" command prompts you to provide values for the connector configuration properties.

After you build a configuration file, you can optionally edit it in a text editor.

You can then create a Connectors instance by using the "connector create" command and providing the name of the configuration file that you built.


....
rhoas connector build [flags]
....

[discrete]
== Examples

....
# Build a Connectors configuration file based on the "aws_lambda_sink_0.1" connector type. The default configuration file name is "connector.json"
rhoas connector build --type=--type=aws_lambda_sink_0.1

# Build a Connectors configuration file named "my_aws_lambda_connector.json" that is based on the "aws_lambda_sink_0.1" connector type
rhoas connector build --name=my_aws_lambda_connector --type=--type=aws_lambda_sink_0.1

....

[discrete]
== Options

      `--name` _string_::          The name of the connector type that was used to build a configuration file
  `-o`, `--output` _string_::      Specify the output format. Choose from: "json", "yaml", "yml"
      `--output-file` _string_::   The filename of the connector configuration file
      `--overwrite`::              Overwrite the file if it aready exists
      `--type` _string_::          The type of the connector in the catalog - this is the same as the ID value for the connector in the catalog

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector_{context}[rhoas connector]	 - Connectors commands

