ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-type-describe_{context}']
= connector type describe

[role="_abstract"]
Get the details of a connector type

[discrete]
== Synopsis

Get the full list of details for a connector type by using its type ID

....
rhoas connector type describe [flags]
....

[discrete]
== Examples

....
# Describe connector type with ID of "slack_source_0.1"
rhoas connector type describe --type=slack_source_0.1 

# Describe the connector type with ID of "slack_source_0.1" and use YAML for the output format
rhoas connector type describe --type=slack_source_0.1 -o yaml

....

[discrete]
== Options

  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"
      `--type` _string_::       The ID of the connector type that you want to get details about

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector-type_{context}[rhoas connector type]	 - View a list of supported connector types

