ifdef::env-github,env-browser[:context: cmd]
[id='ref-dedicated-deregister-cluster_{context}']
= dedicated deregister-cluster

[role="_abstract"]
Deregister an OpenShift cluster with Red Hat OpenShift Streams for Apache Kafka

[discrete]
== Synopsis

Removes the ability to provision your own Kafka instances on a cluster, this command will deregister your 
Hybrid cluster with Red Hat OpenShift Streams for Apache Kafka.


....
rhoas dedicated deregister-cluster [flags]
....

[discrete]
== Examples

....
# Deregister an OpenShift cluster with Red Hat Streams for Apache Kafka by selecting from a list of available clusters.
rhoas cluster deregister-cluster

# Deregister an OpenShift cluster with Red Hat Streams for Apache Kafka by specifying the cluster ID.
rhoas cluster deregister-cluster --cluster-id 1234-5678-90ab-cdef

....

[discrete]
== Options

      `--access-token` _string_::           The access token to use to authenticate with the OpenShift Cluster Management API.
      `--cluster-id` _string_::             The ID of the OpenShift cluster to deregister.
      `--cluster-mgmt-api-url` _string_::   The API URL of the OpenShift Cluster Management API.

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-dedicated_{context}[rhoas dedicated]	 - Manage your Hybrid OpenShift clusters which host your Kafka instances.

