ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact-get_{context}']
= service-registry artifact get

[role="_abstract"]
Get artifact by ID, group, and version

[discrete]
== Synopsis

Get an artifact from the registry based on the artifact ID, group, and version.

NOTE: To fetch artifacts using global identifiers, use the "service-registry artifact download" command.

When --version is specified, the command fetches the specified artifact version. When --version is not specified, the command fetches the latest artifact version.



....
rhoas service-registry artifact get [flags]
....

[discrete]
== Examples

....
## Get latest artifact with name "my-artifact" and print it out to standard out
rhoas service-registry artifact get --artifact-id=my-artifact

## Get latest artifact with name "my-artifact" from group "my-group" and save it to artifact.json file
rhoas service-registry artifact get --artifact-id=my-artifact --group=my-group --output-file=artifact.json

## Get latest artifact and pipe it to another command
rhoas service-registry artifact get --artifact-id=my-artifact | grep -i 'user'

## Get artifact with custom version and print it out to standard out
rhoas service-registry artifact get --artifact-id=myartifact --version=4

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--output-file` _string_::   Location of the output file
      `--version` _string_::       Version of the artifact

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts

