ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-create_{context}']
= connector create

[role="_abstract"]
Create a Connectors instance

[discrete]
== Synopsis

Create a Connectors instance

....
rhoas connector create [flags]
....

[discrete]
== Examples

....
# Create a Connectors instance
rhoas connector create --file=myconnector.json

....

[discrete]
== Options

      `--create-service-account`::   If set, the connector will be created with the newly specified service account
  `-f`, `--file` _string_::          Location of the Connectors JSON file that describes the connector
      `--kafka` _string_::           Id of the kafka instance (by default kafka instance from context would be used)
      `--name` _string_::            Override name of the connector (by default name in the connector spec would be used)
      `--namespace` _string_::       Id of the namespace for the connector (by default namespace from context would be used)
  `-o`, `--output` _string_::        Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector_{context}[rhoas connector]	 - Connectors instance commands

