ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-account-delete_{context}']
= service-account delete

[role="_abstract"]
Delete a service account

[discrete]
== Synopsis

Permanently delete a service account.

When you delete a service account, any applications and tools that use the service account credentials to connect to Kafka instances will no longer be able to connect to them.


....
rhoas service-account delete [flags]
....

[discrete]
== Examples

....
# Delete a service account
$ rhoas service-account delete --id 173c1ad9-932d-4007-ae0f-4da74f4d2ccd

....

[discrete]
== Options

      `--id` _string_::   The unique ID of the service account to delete
  `-y`, `--yes`::         Skip confirmation to forcibly delete this service account

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete, and update service accounts

