ifdef::env-github,env-browser[:context: cmd]
[id='ref-context_{context}']
= context

[role="_abstract"]
Group, share and manage your rhoas services

[discrete]
== Synopsis

Group your service instances into reusable contexts.
Context can be used when running other rhoas commands or to generate service configuration.

A service context is a group of application service instances and their service identifiers. By using service contexts, you can group together application service instances that you want to use together.

After creating a service context, you can share it with other developers so that they can use the same group of application service instances.

You can also use the service context to automatically generate configuration files that you need to use those application service instances in other development platforms and tools. For example, the service context can generate the following types of configurations:

- Standard environment variables for use in local development and tooling
- Java properties files that can be used in Quarkus, Apache Kafka, and so on
- Service binding configuration and service connections for the RHOAS Operator
- Configuration for Helm Charts and Kubernetes

The service context is defined in a JSON file (`contexts.json`), and stored locally on your computer. To find the location of this file, use the "rhoas context status" command.

Note: To specify a custom location for the `contexts.json` file, set the $RHOAS_CONTEXT environment variable to the location you want to use. If you set $RHOAS_CONTEXT to "./rhoas.json", service contexts will be loaded from the current directory.


[discrete]
== Examples

....
# Set the current context
$ rhoas context use --name qa

# List contexts
$ rhoas context list

# Create a context to represent a group of development services
$ rhoas context create --name dev-env

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI

 
* link:{path}#ref-context-create_{context}[context create]	 - Create a service context

 
* link:{path}#ref-context-delete_{context}[context delete]	 - Permanently delete a service context.

 
* link:{path}#ref-context-list_{context}[context list]	 - List service contexts

 
* link:{path}#ref-context-set-connector_{context}[context set-connector]	 - Set the current Connectors instance

 
* link:{path}#ref-context-set-kafka_{context}[context set-kafka]	 - Set the current Kafka instance

 
* link:{path}#ref-context-set-service-registry_{context}[context set-service-registry]	 - Use a Service Registry instance

 
* link:{path}#ref-context-status_{context}[context status]	 - View the status of application services in a service context

 
* link:{path}#ref-context-unset_{context}[context unset]	 - Unset services in context

 
* link:{path}#ref-context-use_{context}[context use]	 - Set the current context

