ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-namespace-use_{context}']
= connector namespace use

[role="_abstract"]
Set the current namespace in context

[discrete]
== Synopsis

Set a namespace as the current working namespace in context. The rhoas CLI uses the
current namespace you run any rhoas connector cluster commands.

You can set a namespace in the current context providing its name or ID.


....
rhoas connector namespace use [flags]
....

[discrete]
== Examples

....
# Set the current namespace by providing the name
$ rhoas connector namespace use --name=my-namespace

# Set the current namespace by providing the ID of a Connectors namespace
$ rhoas connector namespace use --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

....

[discrete]
== Options

      `--id` _string_::     The unique ID of the namespace you want to set as the current namespace
      `--name` _string_::   The name of the namespace you want to set as the current namespace

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector-namespace_{context}[rhoas connector namespace]	 - Connectors namespace commands

