ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-topic-list_{context}']
= kafka topic list

[role="_abstract"]
List all topics

[discrete]
== Synopsis

List all topics in the current Kafka instance.


....
rhoas kafka topic list [flags]
....

[discrete]
== Examples

....
# List all topics
$ rhoas kafka topic list

# List all topics in JSON format
$ rhoas kafka topic list -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"
      `--page` _int32_::        Current page number for list of topics (default 1)
      `--search` _string_::     Text search to filter the Kafka topics by name
      `--size` _int32_::        Maximum number of items to be returned per page (default 10)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list, and delete topics

