ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-topic-update_{context}']
= kafka topic update

[role="_abstract"]
Update configuration details for a Kafka topic

[discrete]
== Synopsis

Update a topic in the current Kafka instance. You can update the cleanup policy, number of partitions, retention size, and retention time.


....
rhoas kafka topic update [flags]
....

[discrete]
== Examples

....
# Update the message retention period for a topic
$ rhoas kafka topic update --name topic-1 --retention-ms -1

....

[discrete]
== Options

      `--cleanup-policy` _string_::    Determines whether log messages are deleted, compacted, or both
      `--instance-id` _string_::       Kafka instance ID. Uses the current instance if not set 
      `--name` _string_::              Topic name
      `--partitions` _string_::        The number of partitions in the topic
      `--retention-bytes` _string_::   The maximum total size of a partition log segments before old log segments are deleted to free up space.
Value of -1 is set by default indicating no retention size limits
      `--retention-ms` _string_::      The period of time in milliseconds the broker will retain a partition log before deleting it

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list, and delete topics

