ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-rule_{context}']
= service-registry rule

[role="_abstract"]
Manage artifact rules in a Service Registry instance

[discrete]
== Synopsis

Set of commands for managing validity and compatibility rules for an entire Service Registry instance or individual for each artifact.
Service Registry rules govern how artifact content can evolve over time by validating for any artifact updates

Rules can be configured as global rules for entire Service Registry instances or specific artifacts.


[discrete]
== Examples

....
## Enable global compatibility rule for artifacts of the current Service Registry instance
$ rhoas service-registry rule enable --rule-type=compatibility --config=full

## Enable global compatibility rule for artifacts of a specific Service Registry instance
$ rhoas service-registry rule enable --rule-type=compatibility --config=full-transitive --instance-id 8ecff228-1ffe-4cf5-b38b-55223885ee00

## display configuration details of global validity rule for current Service Registry instance
$ rhoas service-registry rule describe --rule-type=validity

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - Service Registry commands

 
* link:{path}#ref-service-registry-rule-describe_{context}[service-registry-rule describe]	 - Display configuration of a rule

 
* link:{path}#ref-service-registry-rule-disable_{context}[service-registry-rule disable]	 - Disable validity and compatibility rules

 
* link:{path}#ref-service-registry-rule-enable_{context}[service-registry-rule enable]	 - Enable validity and compatibility rules

 
* link:{path}#ref-service-registry-rule-list_{context}[service-registry-rule list]	 - List validity and compatibility rules

 
* link:{path}#ref-service-registry-rule-update_{context}[service-registry-rule update]	 - Update configuration of rules

