ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-create_{context}']
= kafka create

[role="_abstract"]
Create a Kafka instance

[discrete]
== Synopsis

Create a Kafka instance on a particular cloud provider and region.

After creating the instance you can view it by running "rhoas kafka describe".


....
rhoas kafka create [flags]
....

[discrete]
== Examples

....
# Start an interactive prompt to fill out the configuration values for the instance
$ rhoas kafka create

# Create a Kafka instance
$ rhoas kafka create --name my-kafka-instance

# Create a Kafka instance and output the result in YAML format
$ rhoas kafka create -o yaml

....

[discrete]
== Options

      `--dry-run`::                           Validate all user provided arguments without creating the Kafka instance
      `--marketplace` _string_::              Name of the marketplace where the instance is purchased on
      `--marketplace-account-id` _string_::   Cloud Account ID for the marketplace
      `--name` _string_::                     Unique name of the Kafka instance
  `-o`, `--output` _string_::                 Specify the output format. Choose from: "json", "yaml", "yml"
      `--provider` _string_::                 Cloud Provider ID
      `--region` _string_::                   Cloud Provider Region ID
      `--size` _string_::                     Size of the Kafka instance
      `--use`::                               Set the new Kafka instance to the current instance (default true)
  `-w`, `--wait`::                            Wait until the Kafka instance is created

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances

