ifdef::env-github,env-browser[:context: cmd]
[id='ref-cluster_{context}']
= cluster

[role="_abstract"]
View and perform operations on your Kubernetes or OpenShift cluster

[discrete]
== Synopsis

Connect and bind your services to Kubernetes or OpenShift applications. You can also check if the Kubernetes or OpenShift cluster has the required Operators to perform this operation.

[discrete]
== Examples

....
# Check the status of the connection to your cluster
$ rhoas cluster status

# Connect to cluster without including currently selected services
$ rhoas cluster connect --ignore-context

# Connect to cluster using the specified token
$ rhoas cluster connect --token=value

# Connect to cluster and save script to create service binding
$ rhoas cluster connect --yes > create_service_binding.sh

# Connect managed service with your application
$ rhoas cluster bind

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI

 
* link:{path}#ref-cluster-bind_{context}[cluster bind]	 - Connect your RHOAS services to Kubernetes or OpenShift applications

 
* link:{path}#ref-cluster-clean_{context}[cluster clean]	 - Remove all resources created by cluster extensions

 
* link:{path}#ref-cluster-connect_{context}[cluster connect]	 - Connect your services to Kubernetes or OpenShift

 
* link:{path}#ref-cluster-status_{context}[cluster status]	 - View the status of the current Kubernetes or OpenShift cluster

