ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-list_{context}']
= kafka list

[role="_abstract"]
List all Kafka instances

[discrete]
== Synopsis

List all Kafka instances.

By default, this command lists the Kafka instances in a table, showing the ID, name, owner, status, cloud provider, and region. You can also view the instances in JSON or YAML format.

To view additional details for a particular Kafka instance, use the “rhoas kafka describe” command.


....
rhoas kafka list [flags]
....

[discrete]
== Examples

....
# List all Kafka instances using the default output format
$ rhoas kafka list

# List all Kafka instances in JSON format
$ rhoas kafka list -o json

....

[discrete]
== Options

      `--limit` _int_::         The maximum number of Kafka instances to be returned (default 10)
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"
      `--page` _int_::          Display the Kafka instances from the specified page number (default 1)
      `--search` _string_::     Text search to filter the Kafka instances by name, owner, cloud_provider, region and status

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances

