ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-list_{context}']
= rhoas service-registry artifact list

[role="_abstract"]
[beta] List artifacts

[discrete]
== Synopsis

List all artifacts for the group by specified output format (by default, table)
This command is available as part of the Development Preview release.


....
rhoas service-registry artifact list [flags]
....

[discrete]
== Examples

....
## List all artifacts for the "default" artifact group
rhoas service-registry artifact list

## List all artifacts with "my-group" group
rhoas service-registry artifact list --group=my-group

## List all artifacts with limit and group
rhoas service-registry artifact list --page=2 --limit=10

....

[discrete]
== Options

  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
      `--limit` _int32_::          Page limit (default 100)
  `-o`, `--output` _string_::      Output format (json, yaml, yml)
      `--page` _int32_::           Page number (default 1)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [beta] Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [beta] Manage Service Registry artifacts
endif::[]

