ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-consumer-group-reset-offset_{context}']
= kafka consumer-group reset-offset

[role="_abstract"]
Reset partition offsets for a consumer group

[discrete]
== Synopsis

Reset partition offsets for a particular topic. A reset changes the offset position from which consumers read from the message log of a topic partition. To reset an offset position, the consumer group must have NO MEMBERS connected to a topic.

You can choose from the following options for the reset:
- Earliest (earliest offset at the start of the message log)
- Latest (latest offset at the end of the message log)
- Absolute (specific offset in the message log)
- Timestamp (specific timestamp in the message log)

You can also reset the offset position for all topics or a single, specified topic.

Warning: By resetting the offset position, you risk clients skipping or duplicating messages.


....
rhoas kafka consumer-group reset-offset [flags]
....

[discrete]
== Examples

....
# Reset partition offsets for a consumer group to latest
$ rhoas kafka consumer-group reset-offset --id consumer_group_1 --topic my-topic --offset latest

# Reset partition offsets for a consumer group to earliest
$ rhoas kafka consumer-group reset-offset --id consumer_group_1 --topic my-topic --offset earliest

# Reset partition offsets for a consumer group to an absolute value
$ rhoas kafka consumer-group reset-offset --id consumer_group_1 --topic my-topic --offset absolute --value 0

# Reset partition offsets for a consumer group to a timestamp
$ rhoas kafka consumer-group reset-offset --id consumer_group_1 --topic my-topic --offset timestamp --value "2016-06-23T09:07:21-07:00"

# Reset specific partition offsets for a consumer group
$ rhoas kafka consumer-group reset-offset --id consumer_group_1 --topic my-topic --offset latest --partitions 0,1

....

[discrete]
== Options

      `--id` _string_::               The unique ID of the consumer group to reset-offset
      `--instance-id` _string_::      Kafka instance ID. Uses the current instance if not set 
      `--offset` _string_::           Offset type (choose from: "earliest", "latest", "absolute", "timestamp")
      `--partitions` _int32Slice_::   Reset consumer group offsets on specified partitions (comma-separated integers) (default [])
      `--topic` _string_::            Reset consumer group offsets on a specified topic
      `--value` _string_::            Custom offset value (required when offset is "absolute" or "timestamp")
  `-y`, `--yes`::                     Skip confirmation of this action 

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka-consumer-group_{context}[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance

