ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-consumer-group-delete_{context}']
= kafka consumer-group delete

[role="_abstract"]
Delete a consumer group

[discrete]
== Synopsis

Delete a consumer group from the current Kafka instance.

To select a different Kafka instance, use the “rhoas kafka use” command.


....
rhoas kafka consumer-group delete [flags]
....

[discrete]
== Examples

....
# delete a consumer group
$ rhoas kafka consumer-group delete --id consumer_group_1

....

[discrete]
== Options

      `--id` _string_::            The unique ID of the consumer group to delete
      `--instance-id` _string_::   Kafka instance ID. Uses the current instance if not set 
  `-y`, `--yes`::                  Skip confirmation of this action 

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-kafka-consumer-group_{context}[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance

