ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-type-list_{context}']
= connector type list

[role="_abstract"]
List connector types

[discrete]
== Synopsis

List the types of connectors that are available in the Connectors catalog.'

Use filter options, such as --limit, --page, and --search


....
rhoas connector type list [flags]
....

[discrete]
== Examples

....
# List all connector types
rhoas connector type list

# List connector types with a limit of 10 connector types and 2 pages
rhoas connector type list --limit=10 --page=2

# List all connector types that start with "Amazon"
rhoas connector type list --search=Amazon%

# List all connector types that contain the word "Amazon"
rhoas connector type list --search=%Amazon%

....

[discrete]
== Options

      `--limit` _int_::         Page of the list based on the limit value (default 10)
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"
      `--page` _int_::          Page of the list based on the limit value (default 1)
      `--search` _string_::     Search query for name of connector type

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector-type_{context}[rhoas connector type]	 - View a list of supported connector types

