ifdef::env-github,env-browser[:context: cmd]
= [[ref-rhoas-kafka-topic-list_{context}]]rhoas kafka topic list

[role="_abstract"]
List all topics

[discrete]
== Synopsis

List all topics in the current Apache Kafka instance.


....
rhoas kafka topic list [flags]
....

[discrete]
== Examples

....
# list all topics
$ rhoas kafka topic list

# list all topics as JSON
$ rhoas kafka topic list -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the Kafka topics. Choose from: "json", "yml", "yaml"
      `--search` _string_::     Text search to filter the Kafka topics by name

[discrete]
== Options inherited from parent commands

  `-d`, `--debug`::   Enable debug mode
  `-h`, `--help`::    Show help for a command

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_topic.adoc#user-content-ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list and delete topics
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list and delete topics
endif::[]

