ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-acl-list_{context}']
= rhoas kafka acl list

[role="_abstract"]
List all Kafka ACL rules.

[discrete]
== Synopsis

This command will display list of Kafka ACL rules

The instances are displayed by default in a table, but can also be displayed as JSON or YAML.


....
rhoas kafka acl list [flags]
....

[discrete]
== Examples

....
# Display Kafka ACL rules for the Kafka instance
$ rhoas kafka acl list

# Display Kafka ACL rules for a specific Kafka instance
$ rhoas kafka acl list --instance-id c5hv7iru4an1g84pogp0

....

[discrete]
== Options

      `--instance-id` _string_::   ID of the Kafka instance to be used. By default, uses the currently selected instance
  `-o`, `--output` _string_::      Format in which to display the Kafka ACL rules (choose from: "json", "yml", "yaml")
      `--page` _int32_::           Current page number for list of Kafka ACL rules (default 1)
      `--size` _int32_::           Maximum number of items to be returned per page (default 10)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_acl.adoc#rhoas-kafka-acl[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-acl_{context}[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]

