ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector_{context}']
= connector

[role="_abstract"]
Connectors instance commands

[discrete]
== Synopsis

With Red Hat OpenShift Connectors, you can create and configure connections between Red Hat OpenShift Streams for Apache Kafka and third-party systems. You can configure Connectors that produce data (data source Connectors) and Connectors that specify where to send data (data sink Connectors).

A Connectors instance is an instance of a one of the supported Connectors.
Use the "connector" command to create, delete, and view a list of Connectors instances.


[discrete]
== Examples

....
   
# List of Connectors instances
rhoas connector list

# Create a Connectors instance
rhoas connector create --file=myconnector.json

# Create a Connectors instance from stdin
cat myconnector.json | rhoas connector create

# Update a Connectors instance
rhoas connector update --id=my-connector --file=myconnector.json

# Update a Connectors instance from stdin
cat myconnector.json | rhoas connector update

# Delete a Connectors instance with ID c9b71ucotd37bufoamkg
rhoas connector delete --id=c9b71ucotd37bufoamkg

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI

 
* link:{path}#ref-connector-cluster_{context}[connector cluster]	 - Create, delete, and list Connectors clusters

 
* link:{path}#ref-connector-namespace_{context}[connector namespace]	 - Connectors namespace commands

