ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-role-revoke_{context}']
= service-registry role revoke

[role="_abstract"]
Revoke role for principal

[discrete]
== Synopsis

Revoke the role of a user or service account.

NOTE: It is not possible to revoke the role of the owner of the instance. The instance owner always retains admin rights.


....
rhoas service-registry role revoke [flags]
....

[discrete]
== Examples

....
## Revoke role for user
rhoas service-registry role revoke --username=janedough

....

[discrete]
== Options

      `--instance-id` _string_::       ID of the Service Registry instance to be used (by default, uses the currently selected instance)
      `--service-account` _string_::   ServiceAccount name
      `--username` _string_::          Username of the user within organization

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry-role_{context}[rhoas service-registry role]	 - Service Registry role management

