ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact_{context}']
= service-registry artifact

[role="_abstract"]
Manage Service Registry artifacts

[discrete]
== Synopsis

Manage Service Registry schema and API artifacts in the currently selected Service Registry instance.

Commands are executed on the currently selected Service Registry instance, which can be overridden using the --instance-id flag.

Service Registry enables developers to manage and share the structure of their data.
For example, client applications can dynamically push or pull the latest schema or API updates to or from the registry without needing to redeploy.
Service Registry also enables developers to create rules that govern how registry content can evolve over time.
For example, this includes rules for content validation and version compatibility.

Artifact commands enable client applications to manage the schema and API artifacts in the registry instance.
This set of commands provide create, read, update, and delete operations for artifacts, rules, versions, and metadata.


[discrete]
== Examples

....
## Create artifact in my-group from schema.json file
rhoas service-registry artifact create --artifact-id=my-artifact --group=my-group artifact.json

## Get artifact content
rhoas service-registry artifact get --artifact-id=my-artifact --group=my-group --output-file=artifact.json

## Get artifact content by hash
rhoas service-registry artifact download --hash=cab4...al9 --output-file=artifact.json

## Delete artifact
rhoas service-registry artifact delete --artifact-id=my-artifact

## Get artifact metadata
rhoas service-registry artifact metadata --artifact-id=my-artifact --group=my-group

## Update artifact
rhoas service-registry artifact update --artifact-id=my-artifact artifact-new.json

## List artifacts
rhoas service-registry artifact list --group=my-group --limit=10 page=1

## View artifact versions
rhoas service-registry artifact versions --artifact-id=my-artifact --group=my-group

Artifacts file can be instance of any schema like OpenAPI, Avro etc.
For example: https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json

....

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - Service Registry commands

 
* link:{path}#ref-service-registry-artifact-create_{context}[service-registry-artifact create]	 - Create new artifact from file or standard input

 
* link:{path}#ref-service-registry-artifact-delete_{context}[service-registry-artifact delete]	 - Deletes an artifact or all artifacts in a given group

 
* link:{path}#ref-service-registry-artifact-download_{context}[service-registry-artifact download]	 - Download artifacts from Service Registry using global identifiers

 
* link:{path}#ref-service-registry-artifact-export_{context}[service-registry-artifact export]	 - Export data from Service Registry instance

 
* link:{path}#ref-service-registry-artifact-get_{context}[service-registry-artifact get]	 - Get artifact by ID, group, and version

 
* link:{path}#ref-service-registry-artifact-import_{context}[service-registry-artifact import]	 - Import data into a Service Registry instance

 
* link:{path}#ref-service-registry-artifact-list_{context}[service-registry-artifact list]	 - List artifacts

 
* link:{path}#ref-service-registry-artifact-metadata-get_{context}[service-registry-artifact metadata-get]	 - Get artifact metadata

 
* link:{path}#ref-service-registry-artifact-metadata-set_{context}[service-registry-artifact metadata-set]	 - Update artifact metadata

 
* link:{path}#ref-service-registry-artifact-state-set_{context}[service-registry-artifact state-set]	 - Set artifact state

 
* link:{path}#ref-service-registry-artifact-update_{context}[service-registry-artifact update]	 - Update artifact

 
* link:{path}#ref-service-registry-artifact-versions_{context}[service-registry-artifact versions]	 - Get latest artifact versions by artifact-id and group

