ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-use_{context}']
= service-registry use

[role="_abstract"]
Use a Service Registry instance

[discrete]
== Synopsis

Select a Service Registry instance to use with all instance-specific commands.
You can specify a Service Registry instance by --name or --id.

When you set the Service Registry instance to be used, it is set as the current instance for all rhoas service-registry artifact commands.


....
rhoas service-registry use [flags]
....

[discrete]
== Examples

....
# Use a Service Registry instance by name
rhoas service-registry use --name my-service-registry

# Use a Service Registry instance by ID
rhoas service-registry use --id 1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

....

[discrete]
== Options

      `--id` _string_::     Unique ID of the Service Registry instance you want to set as the current instance
      `--name` _string_::   Name the Service Registry instance you want to set as the current instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - Service Registry commands

