ifdef::env-github,env-browser[:context: cmd]
[id='ref-connector-create_{context}']
= connector create

[role="_abstract"]
Create a Connectors instance

[discrete]
== Synopsis

Create a Connectors instance. 

A Connectors instance is an instance of a one of the supported Connectors.
Use the "connector" command to create, delete, and view a list of Connectors instances.

Before you create a Connectors instance, you must use the "connector build" command to create a configuration file for the type of connector that you want to create. 


....
rhoas connector create [flags]
....

[discrete]
== Examples

....
# Create a Connectors instance by specifying a configuration file
rhoas connector create --file=myconnector.json

....

[discrete]
== Options

      `--create-service-account`::   If set, the connector is created with the specified service account
  `-f`, `--file` _string_::          Location of the Connectors JSON file that describes the connector
      `--kafka` _string_::           ID of the Kafka instance (the default is the Kafka instance for the current context)
      `--name` _string_::            Override the name of the Connectors instance (the default name is the name specified in the connector configuration file)
      `--namespace` _string_::       ID of the namespace for the Connectors instance (the default is the namespace for the current context)
  `-o`, `--output` _string_::        Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


 
* link:{path}#ref-rhoas-connector_{context}[rhoas connector]	 - Connectors commands

