= rhoas kafka describe

[role="_abstract"]
ifdef::env-github,env-browser[:relfilesuffix: .adoc]

View configuration details of an Apache Kafka instance

[discrete]
== Synopsis

View configuration fields and their values for an Apache Kafka instance.

Pass the "--id" flag to specify which instance you would like to view.

If the "--id" flag is not passed then the selected Kafka instance will be used, if available.

You can view the output as either as JSON or YAML.


....
rhoas kafka describe [flags]
....

[discrete]
== Examples

....
# view the current Kafka instance instance
$ rhoas kafka describe

# view a specific instance by passing the --id flag
$ rhoas kafka describe --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# customise the output format
$ rhoas kafka describe -o yaml

....

[discrete]
== Options

      --id:: string       Unique ID of the Kafka instance you want to view. If not set, the current Kafka instance will be used.
  -o, --output:: string   Format in which to display the Kafka instance. Choose from: "json", "yml", "yaml" (default "json")

[discrete]
== Options inherited from parent commands

  -d, --debug::   Enable debug mode
  -h, --help::    Show help for a command

[discrete]
== See also

* link:rhoas_kafka{relfilesuffix}[rhoas kafka]	 - Create, view, use, and manage your Apache Kafka instances

