/*
 * Account Management Service API
 *
 * Manage user subscriptions and clusters
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amsclient

import (
	"encoding/json"
)

// QuotaSummaryListAllOf struct for QuotaSummaryListAllOf
type QuotaSummaryListAllOf struct {
	Items *[]QuotaSummary `json:"items,omitempty"`
}

// NewQuotaSummaryListAllOf instantiates a new QuotaSummaryListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaSummaryListAllOf() *QuotaSummaryListAllOf {
	this := QuotaSummaryListAllOf{}
	return &this
}

// NewQuotaSummaryListAllOfWithDefaults instantiates a new QuotaSummaryListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaSummaryListAllOfWithDefaults() *QuotaSummaryListAllOf {
	this := QuotaSummaryListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *QuotaSummaryListAllOf) GetItems() []QuotaSummary {
	if o == nil || o.Items == nil {
		var ret []QuotaSummary
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaSummaryListAllOf) GetItemsOk() (*[]QuotaSummary, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *QuotaSummaryListAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []QuotaSummary and assigns it to the Items field.
func (o *QuotaSummaryListAllOf) SetItems(v []QuotaSummary) {
	o.Items = &v
}

func (o QuotaSummaryListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableQuotaSummaryListAllOf struct {
	value *QuotaSummaryListAllOf
	isSet bool
}

func (v NullableQuotaSummaryListAllOf) Get() *QuotaSummaryListAllOf {
	return v.value
}

func (v *NullableQuotaSummaryListAllOf) Set(val *QuotaSummaryListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaSummaryListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaSummaryListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaSummaryListAllOf(val *QuotaSummaryListAllOf) *NullableQuotaSummaryListAllOf {
	return &NullableQuotaSummaryListAllOf{value: val, isSet: true}
}

func (v NullableQuotaSummaryListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaSummaryListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
