/*
 * Account Management Service API
 *
 * Manage user subscriptions and clusters
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amsclient

import (
	"encoding/json"
)

// QuotaSummary struct for QuotaSummary
type QuotaSummary struct {
	Href                 *string `json:"href,omitempty"`
	Id                   *string `json:"id,omitempty"`
	Kind                 *string `json:"kind,omitempty"`
	Allowed              int32   `json:"allowed"`
	AvailabilityZoneType string  `json:"availability_zone_type"`
	Byoc                 bool    `json:"byoc"`
	OrganizationId       *string `json:"organization_id,omitempty"`
	Reserved             int32   `json:"reserved"`
	ResourceName         string  `json:"resource_name"`
	ResourceType         string  `json:"resource_type"`
}

// NewQuotaSummary instantiates a new QuotaSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaSummary(allowed int32, availabilityZoneType string, byoc bool, reserved int32, resourceName string, resourceType string) *QuotaSummary {
	this := QuotaSummary{}
	this.Allowed = allowed
	this.AvailabilityZoneType = availabilityZoneType
	this.Byoc = byoc
	this.Reserved = reserved
	this.ResourceName = resourceName
	this.ResourceType = resourceType
	return &this
}

// NewQuotaSummaryWithDefaults instantiates a new QuotaSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaSummaryWithDefaults() *QuotaSummary {
	this := QuotaSummary{}
	return &this
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *QuotaSummary) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *QuotaSummary) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *QuotaSummary) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *QuotaSummary) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *QuotaSummary) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *QuotaSummary) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *QuotaSummary) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *QuotaSummary) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *QuotaSummary) SetKind(v string) {
	o.Kind = &v
}

// GetAllowed returns the Allowed field value
func (o *QuotaSummary) GetAllowed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetAllowedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Allowed, true
}

// SetAllowed sets field value
func (o *QuotaSummary) SetAllowed(v int32) {
	o.Allowed = v
}

// GetAvailabilityZoneType returns the AvailabilityZoneType field value
func (o *QuotaSummary) GetAvailabilityZoneType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvailabilityZoneType
}

// GetAvailabilityZoneTypeOk returns a tuple with the AvailabilityZoneType field value
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetAvailabilityZoneTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailabilityZoneType, true
}

// SetAvailabilityZoneType sets field value
func (o *QuotaSummary) SetAvailabilityZoneType(v string) {
	o.AvailabilityZoneType = v
}

// GetByoc returns the Byoc field value
func (o *QuotaSummary) GetByoc() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Byoc
}

// GetByocOk returns a tuple with the Byoc field value
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetByocOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Byoc, true
}

// SetByoc sets field value
func (o *QuotaSummary) SetByoc(v bool) {
	o.Byoc = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *QuotaSummary) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *QuotaSummary) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *QuotaSummary) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetReserved returns the Reserved field value
func (o *QuotaSummary) GetReserved() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Reserved
}

// GetReservedOk returns a tuple with the Reserved field value
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetReservedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reserved, true
}

// SetReserved sets field value
func (o *QuotaSummary) SetReserved(v int32) {
	o.Reserved = v
}

// GetResourceName returns the ResourceName field value
func (o *QuotaSummary) GetResourceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetResourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceName, true
}

// SetResourceName sets field value
func (o *QuotaSummary) SetResourceName(v string) {
	o.ResourceName = v
}

// GetResourceType returns the ResourceType field value
func (o *QuotaSummary) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *QuotaSummary) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *QuotaSummary) SetResourceType(v string) {
	o.ResourceType = v
}

func (o QuotaSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["allowed"] = o.Allowed
	}
	if true {
		toSerialize["availability_zone_type"] = o.AvailabilityZoneType
	}
	if true {
		toSerialize["byoc"] = o.Byoc
	}
	if o.OrganizationId != nil {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if true {
		toSerialize["reserved"] = o.Reserved
	}
	if true {
		toSerialize["resource_name"] = o.ResourceName
	}
	if true {
		toSerialize["resource_type"] = o.ResourceType
	}
	return json.Marshal(toSerialize)
}

type NullableQuotaSummary struct {
	value *QuotaSummary
	isSet bool
}

func (v NullableQuotaSummary) Get() *QuotaSummary {
	return v.value
}

func (v *NullableQuotaSummary) Set(val *QuotaSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaSummary(val *QuotaSummary) *NullableQuotaSummary {
	return &NullableQuotaSummary{value: val, isSet: true}
}

func (v NullableQuotaSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
