/*
 * Account Management Service API
 *
 * Manage user subscriptions and clusters
 *
 * API version: 0.0.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amsclient

import (
	"encoding/json"
)

// CapabilityAllOf struct for CapabilityAllOf
type CapabilityAllOf struct {
	Inherited bool   `json:"inherited"`
	Name      string `json:"name"`
	Value     string `json:"value"`
}

// NewCapabilityAllOf instantiates a new CapabilityAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilityAllOf(inherited bool, name string, value string) *CapabilityAllOf {
	this := CapabilityAllOf{}
	this.Inherited = inherited
	this.Name = name
	this.Value = value
	return &this
}

// NewCapabilityAllOfWithDefaults instantiates a new CapabilityAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityAllOfWithDefaults() *CapabilityAllOf {
	this := CapabilityAllOf{}
	return &this
}

// GetInherited returns the Inherited field value
func (o *CapabilityAllOf) GetInherited() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Inherited
}

// GetInheritedOk returns a tuple with the Inherited field value
// and a boolean to check if the value has been set.
func (o *CapabilityAllOf) GetInheritedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inherited, true
}

// SetInherited sets field value
func (o *CapabilityAllOf) SetInherited(v bool) {
	o.Inherited = v
}

// GetName returns the Name field value
func (o *CapabilityAllOf) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CapabilityAllOf) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CapabilityAllOf) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CapabilityAllOf) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CapabilityAllOf) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CapabilityAllOf) SetValue(v string) {
	o.Value = v
}

func (o CapabilityAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["inherited"] = o.Inherited
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCapabilityAllOf struct {
	value *CapabilityAllOf
	isSet bool
}

func (v NullableCapabilityAllOf) Get() *CapabilityAllOf {
	return v.value
}

func (v *NullableCapabilityAllOf) Set(val *CapabilityAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilityAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilityAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilityAllOf(val *CapabilityAllOf) *NullableCapabilityAllOf {
	return &NullableCapabilityAllOf{value: val, isSet: true}
}

func (v NullableCapabilityAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilityAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
