/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amsclient

import (
	"encoding/json"
)

// QuotaCostAllOf struct for QuotaCostAllOf
type QuotaCostAllOf struct {
	Allowed int32 `json:"allowed"`
	Consumed int32 `json:"consumed"`
	OrganizationId *string `json:"organization_id,omitempty"`
	QuotaId string `json:"quota_id"`
	RelatedResources *[]RelatedResource `json:"related_resources,omitempty"`
}

// NewQuotaCostAllOf instantiates a new QuotaCostAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaCostAllOf(allowed int32, consumed int32, quotaId string) *QuotaCostAllOf {
	this := QuotaCostAllOf{}
	this.Allowed = allowed
	this.Consumed = consumed
	this.QuotaId = quotaId
	return &this
}

// NewQuotaCostAllOfWithDefaults instantiates a new QuotaCostAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaCostAllOfWithDefaults() *QuotaCostAllOf {
	this := QuotaCostAllOf{}
	return &this
}

// GetAllowed returns the Allowed field value
func (o *QuotaCostAllOf) GetAllowed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value
// and a boolean to check if the value has been set.
func (o *QuotaCostAllOf) GetAllowedOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Allowed, true
}

// SetAllowed sets field value
func (o *QuotaCostAllOf) SetAllowed(v int32) {
	o.Allowed = v
}

// GetConsumed returns the Consumed field value
func (o *QuotaCostAllOf) GetConsumed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Consumed
}

// GetConsumedOk returns a tuple with the Consumed field value
// and a boolean to check if the value has been set.
func (o *QuotaCostAllOf) GetConsumedOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Consumed, true
}

// SetConsumed sets field value
func (o *QuotaCostAllOf) SetConsumed(v int32) {
	o.Consumed = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *QuotaCostAllOf) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaCostAllOf) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *QuotaCostAllOf) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *QuotaCostAllOf) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetQuotaId returns the QuotaId field value
func (o *QuotaCostAllOf) GetQuotaId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuotaId
}

// GetQuotaIdOk returns a tuple with the QuotaId field value
// and a boolean to check if the value has been set.
func (o *QuotaCostAllOf) GetQuotaIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QuotaId, true
}

// SetQuotaId sets field value
func (o *QuotaCostAllOf) SetQuotaId(v string) {
	o.QuotaId = v
}

// GetRelatedResources returns the RelatedResources field value if set, zero value otherwise.
func (o *QuotaCostAllOf) GetRelatedResources() []RelatedResource {
	if o == nil || o.RelatedResources == nil {
		var ret []RelatedResource
		return ret
	}
	return *o.RelatedResources
}

// GetRelatedResourcesOk returns a tuple with the RelatedResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuotaCostAllOf) GetRelatedResourcesOk() (*[]RelatedResource, bool) {
	if o == nil || o.RelatedResources == nil {
		return nil, false
	}
	return o.RelatedResources, true
}

// HasRelatedResources returns a boolean if a field has been set.
func (o *QuotaCostAllOf) HasRelatedResources() bool {
	if o != nil && o.RelatedResources != nil {
		return true
	}

	return false
}

// SetRelatedResources gets a reference to the given []RelatedResource and assigns it to the RelatedResources field.
func (o *QuotaCostAllOf) SetRelatedResources(v []RelatedResource) {
	o.RelatedResources = &v
}

func (o QuotaCostAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["allowed"] = o.Allowed
	}
	if true {
		toSerialize["consumed"] = o.Consumed
	}
	if o.OrganizationId != nil {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if true {
		toSerialize["quota_id"] = o.QuotaId
	}
	if o.RelatedResources != nil {
		toSerialize["related_resources"] = o.RelatedResources
	}
	return json.Marshal(toSerialize)
}

type NullableQuotaCostAllOf struct {
	value *QuotaCostAllOf
	isSet bool
}

func (v NullableQuotaCostAllOf) Get() *QuotaCostAllOf {
	return v.value
}

func (v *NullableQuotaCostAllOf) Set(val *QuotaCostAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaCostAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaCostAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaCostAllOf(val *QuotaCostAllOf) *NullableQuotaCostAllOf {
	return &NullableQuotaCostAllOf{value: val, isSet: true}
}

func (v NullableQuotaCostAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaCostAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


