/*
Account Management Service API

Manage user subscriptions and clusters

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amsclient

import (
	"encoding/json"
)

// RoleBindingCreateRequest struct for RoleBindingCreateRequest
type RoleBindingCreateRequest struct {
	AccountId string `json:"account_id"`
	ConfigManaged *bool `json:"config_managed,omitempty"`
	OrganizationId *string `json:"organization_id,omitempty"`
	RoleId string `json:"role_id"`
	SubscriptionId *string `json:"subscription_id,omitempty"`
	Type string `json:"type"`
}

// NewRoleBindingCreateRequest instantiates a new RoleBindingCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleBindingCreateRequest(accountId string, roleId string, type_ string) *RoleBindingCreateRequest {
	this := RoleBindingCreateRequest{}
	this.AccountId = accountId
	this.RoleId = roleId
	this.Type = type_
	return &this
}

// NewRoleBindingCreateRequestWithDefaults instantiates a new RoleBindingCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleBindingCreateRequestWithDefaults() *RoleBindingCreateRequest {
	this := RoleBindingCreateRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *RoleBindingCreateRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *RoleBindingCreateRequest) GetAccountIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *RoleBindingCreateRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetConfigManaged returns the ConfigManaged field value if set, zero value otherwise.
func (o *RoleBindingCreateRequest) GetConfigManaged() bool {
	if o == nil || o.ConfigManaged == nil {
		var ret bool
		return ret
	}
	return *o.ConfigManaged
}

// GetConfigManagedOk returns a tuple with the ConfigManaged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingCreateRequest) GetConfigManagedOk() (*bool, bool) {
	if o == nil || o.ConfigManaged == nil {
		return nil, false
	}
	return o.ConfigManaged, true
}

// HasConfigManaged returns a boolean if a field has been set.
func (o *RoleBindingCreateRequest) HasConfigManaged() bool {
	if o != nil && o.ConfigManaged != nil {
		return true
	}

	return false
}

// SetConfigManaged gets a reference to the given bool and assigns it to the ConfigManaged field.
func (o *RoleBindingCreateRequest) SetConfigManaged(v bool) {
	o.ConfigManaged = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *RoleBindingCreateRequest) GetOrganizationId() string {
	if o == nil || o.OrganizationId == nil {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingCreateRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil || o.OrganizationId == nil {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *RoleBindingCreateRequest) HasOrganizationId() bool {
	if o != nil && o.OrganizationId != nil {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *RoleBindingCreateRequest) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetRoleId returns the RoleId field value
func (o *RoleBindingCreateRequest) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *RoleBindingCreateRequest) GetRoleIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *RoleBindingCreateRequest) SetRoleId(v string) {
	o.RoleId = v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *RoleBindingCreateRequest) GetSubscriptionId() string {
	if o == nil || o.SubscriptionId == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleBindingCreateRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || o.SubscriptionId == nil {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *RoleBindingCreateRequest) HasSubscriptionId() bool {
	if o != nil && o.SubscriptionId != nil {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *RoleBindingCreateRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetType returns the Type field value
func (o *RoleBindingCreateRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RoleBindingCreateRequest) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RoleBindingCreateRequest) SetType(v string) {
	o.Type = v
}

func (o RoleBindingCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["account_id"] = o.AccountId
	}
	if o.ConfigManaged != nil {
		toSerialize["config_managed"] = o.ConfigManaged
	}
	if o.OrganizationId != nil {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if true {
		toSerialize["role_id"] = o.RoleId
	}
	if o.SubscriptionId != nil {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableRoleBindingCreateRequest struct {
	value *RoleBindingCreateRequest
	isSet bool
}

func (v NullableRoleBindingCreateRequest) Get() *RoleBindingCreateRequest {
	return v.value
}

func (v *NullableRoleBindingCreateRequest) Set(val *RoleBindingCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleBindingCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleBindingCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleBindingCreateRequest(val *RoleBindingCreateRequest) *NullableRoleBindingCreateRequest {
	return &NullableRoleBindingCreateRequest{value: val, isSet: true}
}

func (v NullableRoleBindingCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleBindingCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


