// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package connection

import (
	"context"
	"github.com/bf2fc6cc711aee1a0c2a/cli/pkg/api/managedservices"
	"sync"
)

// Ensure, that ConnectionMock does implement Connection.
// If this is not the case, regenerate this file with moq.
var _ Connection = &ConnectionMock{}

// ConnectionMock is a mock implementation of Connection.
//
//     func TestSomethingThatUsesIConnection(t *testing.T) {
//
//         // make and configure a mocked Connection
//         mockedIConnection := &ConnectionMock{
//             LogoutFunc: func(ctx context.Context) error {
// 	               panic("mock out the Logout method")
//             },
//             NewAPIClientFunc: func() *managedservices.APIClient {
// 	               panic("mock out the NewAPIClient method")
//             },
//             RefreshTokensFunc: func(ctx context.Context) (string, string, error) {
// 	               panic("mock out the RefreshTokens method")
//             },
//         }
//
//         // use mockedIConnection in code that requires Connection
//         // and then make assertions.
//
//     }
type ConnectionMock struct {
	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context) error

	// NewAPIClientFunc mocks the NewAPIClient method.
	NewAPIClientFunc func() *managedservices.APIClient

	// RefreshTokensFunc mocks the RefreshTokens method.
	RefreshTokensFunc func(ctx context.Context) (string, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// NewAPIClient holds details about calls to the NewAPIClient method.
		NewAPIClient []struct {
		}
		// RefreshTokens holds details about calls to the RefreshTokens method.
		RefreshTokens []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockLogout        sync.RWMutex
	lockNewAPIClient  sync.RWMutex
	lockRefreshTokens sync.RWMutex
}

// Logout calls LogoutFunc.
func (mock *ConnectionMock) Logout(ctx context.Context) error {
	if mock.LogoutFunc == nil {
		panic("ConnectionMock.LogoutFunc: method is nil but Connection.Logout was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//     len(mockedIConnection.LogoutCalls())
func (mock *ConnectionMock) LogoutCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// NewAPIClient calls NewAPIClientFunc.
func (mock *ConnectionMock) NewAPIClient() *managedservices.APIClient {
	if mock.NewAPIClientFunc == nil {
		panic("ConnectionMock.NewAPIClientFunc: method is nil but Connection.NewAPIClient was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNewAPIClient.Lock()
	mock.calls.NewAPIClient = append(mock.calls.NewAPIClient, callInfo)
	mock.lockNewAPIClient.Unlock()
	return mock.NewAPIClientFunc()
}

// NewAPIClientCalls gets all the calls that were made to NewAPIClient.
// Check the length with:
//     len(mockedIConnection.NewAPIClientCalls())
func (mock *ConnectionMock) NewAPIClientCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNewAPIClient.RLock()
	calls = mock.calls.NewAPIClient
	mock.lockNewAPIClient.RUnlock()
	return calls
}

// RefreshTokens calls RefreshTokensFunc.
func (mock *ConnectionMock) RefreshTokens(ctx context.Context) (string, string, error) {
	if mock.RefreshTokensFunc == nil {
		panic("ConnectionMock.RefreshTokensFunc: method is nil but Connection.RefreshTokens was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRefreshTokens.Lock()
	mock.calls.RefreshTokens = append(mock.calls.RefreshTokens, callInfo)
	mock.lockRefreshTokens.Unlock()
	return mock.RefreshTokensFunc(ctx)
}

// RefreshTokensCalls gets all the calls that were made to RefreshTokens.
// Check the length with:
//     len(mockedIConnection.RefreshTokensCalls())
func (mock *ConnectionMock) RefreshTokensCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRefreshTokens.RLock()
	calls = mock.calls.RefreshTokens
	mock.lockRefreshTokens.RUnlock()
	return calls
}
