== Using Kafkacat with Managed Kafka Quickstart

This project illustrates how you can interact with a Managed Kafka using
https://github.com/edenhill/kafkacat[Kafkacat].

=== Prequisite

* https://github.com/edenhill/kafkacat[Kafkacat]
* https://stedolan.github.io/jq/[jq]
* https://github.com/bf2fc6cc711aee1a0c2a/cli/releases[rhoas cli]
* https://kubernetes.io/fr/docs/reference/kubectl/overview/[kubectl].
This is temporary required

=== Spinning a Managed Kafka cluster

First you need a Kafka cluster. You can follow the instructions to
create one.

Using the https://github.com/bf2fc6cc711aee1a0c2a/cli/releases[RHMAS
CLI], login and create a new cluster:

[source,bash]
----
rhoas login
rhoas kafka create --name=<your-cluster-name>
----

Wait a couple of seconds for cluster to provision.

You can use the:

[source,bash]
----
rhoas kafka list
----

to check the status of the provisioned Kafka.

At the moment we are missing the certificates, since this is not
returned by the API. To retrieve them, we’ll need `kubectl` and access
to the staging environment.

The rest of the commands assumes that you are logged in to the staging
environment OSD cluster.

____
NOTE: Certificates retrieval part will be automated by the CLI (We’ll
need some work on the API front).
____

Retrieve certificates.

[source,bash]
----
kubectl get secret <cluster-name>-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > /tmp/ca.cert
----

=== Retrieve Bootstrap URL

[source,bash]
----
CLUSTER_ID=$(rhoas kafka list | grep '<your-cluster-name>' | awk '{print $1}')
BOOTSTRAP_URL=$(rhoas kafka get $CLUSTER_ID | jq -r '.bootstrapServerHost')
----

Where `<your-cluster-name>` is the name of the cluster.

=== Produce a message.

[source,bash]
----
kafkacat -t my-topic -b "$BOOTSTRAP_URL:443" -X security.protocol=SSL -X ssl.ca.location=/tmp/ca.cert -P

First message
Second message
Third message
----

=== Consume a message.

start the consumer

[source,bash]
----
kafkacat -t my-topic -b "$BOOTSTRAP_URL:443" -X security.protocol=SSL -X ssl.ca.location=/tmp/ca.cert -C
----

You should see

[source,log]
----
First message
Second message
Third message
----
