/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msclient

// KafkaRequestList struct for KafkaRequestList
type KafkaRequestList struct {
	Kind  string         `json:"kind"`
	Page  int32          `json:"page"`
	Size  int32          `json:"size"`
	Total int32          `json:"total"`
	Items []KafkaRequest `json:"items"`
}
