/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msclient

// KafkaRequestListAllOf struct for KafkaRequestListAllOf
type KafkaRequestListAllOf struct {
	Items []KafkaRequest `json:"items,omitempty"`
}
