ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-describe_{context}']
= kafka describe

[role="_abstract"]
View configuration details of a Kafka instance

[discrete]
== Synopsis

View configuration details for a Kafka instance.

Use the "--id" flag to specify which instance you would like to view.

If the "--id" flag is not used then the selected Kafka instance will be used, if available.

You can view the output either as JSON or YAML.

To view a list of all Kafka instances, use the “rhoas kafka list” command.


....
rhoas kafka describe [flags]
....

[discrete]
== Examples

....
# View the current Kafka instance
$ rhoas kafka describe

# View a specific instance by ID
$ rhoas kafka describe --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# View a specific instance by name
$ rhoas kafka describe --name=my-kafka

# Customize the output format
$ rhoas kafka describe -o yaml

....

[discrete]
== Options

      `--bootstrap-server`::    If specified, only the bootstrap server host of the Kafka instance will be displayed
      `--id` _string_::         Unique ID of the Kafka instance you want to view
      `--name` _string_::       Name of the Kafka instance you want to view
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka.adoc#rhoas-kafka[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]

