ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka-consumer-group-describe_{context}']
= kafka consumer-group describe

[role="_abstract"]
Describe a consumer group

[discrete]
== Synopsis

View detailed information for a consumer group and its members.


....
rhoas kafka consumer-group describe [flags]
....

[discrete]
== Examples

....
# describe a consumer group
$ rhoas kafka consumer-group describe --id consumer_group_1 -o json

....

[discrete]
== Options

      `--id` _string_::         The unique ID of the consumer group to view
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_consumer-group.adoc#rhoas-kafka-consumer-group[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-consumer-group_{context}[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance
endif::[]

