ifdef::env-github,env-browser[:context: cmd]
[id='ref-kafka_topic_describe_{context}']
= kafka_topic_describe

[role="_abstract"]
Describe a topic

[discrete]
== Synopsis

Print detailed configuration information for a Kafka topic.


....
rhoas kafka topic describe [flags]
....

[discrete]
== Examples

....
# describe a topic
$ rhoas kafka topic describe --name topic-1

....

[discrete]
== Options

      `--name` _string_::       Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
  `-o`, `--output` _string_::   Specify the output format. Choose from: "json", "yaml", "yml"

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_topic.adoc#rhoas-kafka-topic[rhoas kafka topic]	 - Create, describe, update, list and delete topics
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list and delete topics
endif::[]

