== rhoas completion

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Generate completion script

=== Synopsis

To load completions:
	
	Bash:
	
	$ source <(rhoas completion bash)
	
	# To load completions for each session, execute once:
	Linux:
		$ rhoas completion bash > /etc/bash_completion.d/rhoas
	MacOS:
		$ rhoas completion bash > /usr/local/etc/bash_completion.d/rhoas
	
	Zsh:
	
	# If shell completion is not already enabled in your environment you will need
	# to enable it.  You can execute the following once:
	
	$ echo "autoload -U compinit; compinit" >> ~/.zshrc
	
	# To load completions for each session, execute once:
	$ rhoas completion zsh > "${fpath[1]}/_rhoas"
	
	# You will need to start a new shell for this setup to take effect.
	
	Fish:
	
	$ rhoas completion fish | source
	
	# To load completions for each session, execute once:
	$ rhoas completion fish > ~/.config/fish/completions/rhoas.fish



....
rhoas completion [bash|zsh|fish|powershell]
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas{relfilesuffix}[rhoas]	 - RHOAS CLI

