= rhoas cluster connect

[role="_abstract"]
ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Connect your services to Kubernetes or OpenShift

[discrete]
== Synopsis

Connect your application services to your Kubernetes or OpenShift cluster.
The kubeconfig file is used to connect to the cluster and identify the context.
Alternatively, you can use the KUBECONFIG environment variable to read your configuration.

NOTE: This command requires the RHOAS operator to be running on your cluster.

This command will:

1. Create a service account and mount it as a secret into your cluster.
If the cluster has a service account, it will be refreshed.

2. Create a Kafka Request object that can be used to create a ServiceBinding object using
the Service Binding operator (https://github.com/redhat-developer/service-binding-operator).



....
rhoas cluster connect [flags]
....

[discrete]
== Examples

....
# connect the current Kafka instance to your cluster
$ rhoas cluster connect

....

[discrete]
== Options

      --ignore-context::      Ignore currently selected services and ask to select each service separately
      --kubeconfig:: string   Location of the kubeconfig file.
  -n, --namespace:: string    Custom Kubernetes namespace (if not set current namespace will be used)
      --token:: string        Provide an offline token to be used by the operator. To obtain a token, visit https://cloud.redhat.com/openshift/token.

  -y, --yes::                 Forcibly create a binding without confirmation.

[discrete]
== Options inherited from parent commands

  -d, --debug::   Enable debug mode
  -h, --help::    Show help for a command

[discrete]
== See also

* link:rhoas_cluster{relfilesuffix}[rhoas cluster]	 - View and perform operations on your Kubernetes or OpenShift cluster

