= rhoas completion bash

[role="_abstract"]
ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Generate command completion script for Bash shell

[discrete]
== Synopsis

Generate command completion script for Bash shell.

Installing on Linux:

1. Run `rhoas completion bash > rhoas_completions` to create the script file.
2. Run `sudo mv rhoas_completions /etc/bash_completion.d/rhoas` to place the script in a special Bash completions directory.

Installing on macOS:

1. Run `rhoas completion bash > rhoas_completions` to create the script file.
2. Run `sudo mv rhoas_completions /usr/local/etc/bash_completion.d/rhoas` to place the script in a special Bash completions directory.


....
rhoas completion bash
....

[discrete]
== Options inherited from parent commands

  -d, --debug::   Enable debug mode
  -h, --help::    Show help for a command

[discrete]
== See also

* link:rhoas_completion{relfilesuffix}[rhoas completion]	 - Outputs command completion for the given shell (bash, zsh, or fish)

