ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-delete_{context}']
= rhoas service-registry delete

[role="_abstract"]
[beta] Delete a Service Registry instance

[discrete]
== Synopsis

 
Delete a Service Registry instance along with all of its schema and API artifacts.

This command is available as part of the Development Preview release.


....
rhoas service-registry delete [flags]
....

[discrete]
== Examples

....
# Delete a Service Registry instance by name
rhoas service-registry delete --name my-service-registry

# Delete a Service Registry instance by ID
rhoas service-registry delete --id 1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

....

[discrete]
== Options

      `--id` _string_::     Unique ID of the Service Registry instance you want to delete (if not provided, the current Service Registry instance will be deleted)
      `--name` _string_::   Name of the Service Registry instance to delete
  `-y`, `--yes`::           Skip confirmation to forcibly delete this Service Registry instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [beta] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [beta] Service Registry commands
endif::[]

