== rhoas serviceaccount create

Create a new service account with credentials

=== Synopsis

Creates a new service account with SASL/PLAIN credentials to connect
your application to services. The credentials are saved to an output
format of your choice from the list below with the –output flag:

....
- env (default): Saves the credentials to a .env file as environment variables
- kafka, properties: Saves the credentials to a kafka.properties file
- json: Saves the credentials in a credentials.json JSON file
- kube: Saves credentials as Kubernetes secret
....

....
rhoas serviceaccount create [flags]
....

=== Examples

....
$ rhoas serviceaccount create --output kafka
$ rhoas serviceaccount create --output=env
$ rhoas serviceaccount create -o=properties
$ rhoas serviceaccount create -o env --force
$ rhoas serviceaccount create -o json
....

=== Options

....
      --description string     Description for the service account
      --file-location string   Sets a custom file location to save the credentials
  -h, --help                   help for create
      --name string            Name of the service account
  -o, --output string          Format of the config [env, kafka, properties, json, kube] (default "env")
      --overwrite              Force overwrite a file if it already exists
      --scopes stringArray     Number of supported scopes (permissions) for this service account (default [kafka-all])
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_serviceaccount.adoc[rhoas serviceaccount] - Manage your
service accounts

==== Auto generated by spf13/cobra on 14-Jan-2021
