== rhoas serviceaccount

Create, list, delete and update service accounts

=== Synopsis

Use these commands to create, delete, and list service accounts. You can
also reset the credentials for service account.

=== Examples

....
# create a service account
$ rhoas serviceaccount creare

# list service accounts
$ rhoas serviceaccount list

# delete a service account
$ rhoas serviceaccount delete --id "173c1ad9-932d-4007-ae0f-4da74f4d2ccd"

# reset credentials on a service account
$ rhoas serviceaccount reset-credentials
....

=== Options

....
  -h, --help   help for serviceaccount
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas.adoc[rhoas] - RHOAS CLI
* link:rhoas_serviceaccount_create.adoc[rhoas serviceaccount create] -
Create a service account
* link:rhoas_serviceaccount_delete.adoc[rhoas serviceaccount delete] -
Delete a service account
* link:rhoas_serviceaccount_list.adoc[rhoas serviceaccount list] - List
service accounts
* link:rhoas_serviceaccount_reset-credentials.adoc[rhoas serviceaccount
reset-credentials] - Reset service account credentials

