ifdef::env-github,env-browser[:context: cmd]
= [[ref-rhoas-status_{context}]]rhoas status

[role="_abstract"]
View the status of all currently used services

[discrete]
== Synopsis

View status information of your currently used services.
Choose to view the status of all services with "rhoas status" or specific services with "rhoas status [service]"

To use a different service run "rhoas <service> use [args] [flags]".


....
rhoas status [args] [flags]
....

[discrete]
== Examples

....
# view the status of all services
$ rhoas status

# view the status of the used Kafka
$ rhoas status kafka

# view the status of your services in JSON
$ rhoas status -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the status of your services. Choose from: "json", "yml", "yaml"

[discrete]
== Options inherited from parent commands

  `-d`, `--debug`::   Enable debug mode
  `-h`, `--help`::    Show help for a command

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas.adoc#user-content-ref-rhoas_{context}[rhoas]	 - RHOAS CLI
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas_{context}[rhoas]	 - RHOAS CLI
endif::[]

