== rhoas cluster connect

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Connect your services to Kubernetes or OpenShift

=== Synopsis

Connect your application services to your Kubernetes or OpenShift cluster.
The kubeconfig file is used to connect to the cluster and identify the context.
Alternatively, you can use the KUBECONFIG environment variable to read your configuration.

NOTE: This command requires the RHOAS operator to be running on your cluster.

This command will:

1. Create a service account and mount it as a secret into your cluster. 
If the cluster has a service account, it will be refreshed.

2. Create a Managed Kafka Request object that can be used to create a ServiceBinding object using 
the Service Binding operator.
https://github.com/redhat-developer/service-binding-operator



....
rhoas cluster connect [flags]
....

=== Examples

....
# connect the current Kafka instance to your cluster
$ rhoas cluster connect

....

=== Options

....
      --kubeconfig string   Location of the kubeconfig file.
      --token string        Provide an offline token to be used by the operator.
                            To get a token, visit https://cloud.redhat.com/openshift/token.
                            
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_cluster{relfilesuffix}[rhoas cluster]	 - View and perform operations on your Kubernetes or OpenShift cluster

