== rhoas serviceaccount reset-credentials

Reset service account credentials

=== Synopsis

Reset the SASL/PLAIN credentials for a service account.

This command will generate a new SASL/PLAIN password for a service
account. Once the credentials have been reset, any applications or tools
that use the SASL/PLAIN credentials will need to be updated with the new
password for it to work again.

....
rhoas serviceaccount reset-credentials [flags]
....

=== Examples

....
# start an interactive prompt to reset credentials
$ rhoas serviceaccount reset-credentials

# reset credentials for the service account specified and save the credentials to a JSON file
$ rhoas serviceaccount reset-credentials --id 173c1ad9-932d-4007-ae0f-4da74f4d2ccd -o json
....

=== Options

....
      --file-location string   Sets a custom file location to save the credentials
  -h, --help                   help for reset-credentials
      --id string              The unique ID of the service account to delete
  -o, --output string          Format of the credentials file: ["env" "json" "properties" "kube"]
      --overwrite              Force overwrite a credentials file if it already exists
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_serviceaccount.adoc[rhoas serviceaccount] - Create, list,
delete and update service accounts

