== rhoas serviceaccount create

Create a service account

=== Synopsis

Create a service account with credentials which are saved to a file.

The credentials generated as part of a service account can be by
applications and tools to authenticate and interact with services.

You must specify an output format to which the credentials will be
stored as. - env (default: Store credentials in an env file as
environment variables - json: Store credentials in a JSON file - kube:
Store credentials as a Kubernetes secret file (the secret is not created
for you) - properties: Store credentials in a properties file, mainly
used in Java-related technologies.

....
rhoas serviceaccount create [flags]
....

=== Examples

....
# create a service account through an interactive prompt
$ rhoas serviceaccount create

# create a service account and save the credentials in a Kubernetes secret file format
$ rhoas serviceaccount create --output kube

# create a service account and forcefully overwrite the credentials file if it exists already
$ rhoas serviceaccount create --overwrite

# create a service account and save credentials to a custom file location
$ rhoas serviceaccount create --file-location=./service-acct-credentials.json
....

=== Options

....
      --description string     Description for the service account
      --file-location string   Sets a custom file location to save the credentials
  -h, --help                   help for create
      --name string            Name of the service account
  -o, --output string          Format of the credentials file: ["env" "json" "properties" "kube"]
      --overwrite              Force overwrite a credentials file if it already exists
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_serviceaccount.adoc[rhoas serviceaccount] - Create, list,
delete and update service accounts

