== rhoas login

Login to Managed Application Services

=== Synopsis

Login to Managed Application Services in order to manage your services

....
rhoas login [flags]
....

=== Options

....
      --auth-url string    SSO Authentication server (default "https://sso.redhat.com/auth/realms/redhat-external")
      --client-id string   OpenID client identifier. (default "rhoas-cli-prod")
  -h, --help               help for login
      --insecure           Enables insecure communication with the server. This disables verification of TLS certificates and host names.
      --print-sso-url      Prints the login URL to the console so you can control which browser to open it in. Useful if you need to log in with a user that is different to the one logged in on your default web browser.
      --url string         URL of the API gateway. The value can be the complete URL or an alias. The valid aliases are 'production', 'staging', 'integration', 'development' and their shorthands. (default "https://api.stage.openshift.com")
....

=== SEE ALSO

* link:rhoas.adoc[rhoas] - rhoas cli

==== Auto generated by spf13/cobra on 14-Dec-2020
