== rhoas serviceaccount reset-credentials

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Reset service account credentials

=== Synopsis

Reset the credentials for a service account.
This command will generate a new password for a service account.
After the credentials have been reset, any applications or tools that use the
credentials must be updated to use the new password.

You must specify an output format into which the credentials will be stored.
  - env (default): Store credentials in an env file as environment variables
  - json: Store credentials in a JSON file
  - kubernetes-secret: Store credentials in YAML as a Kubernetes Secret (the Kubernetes Secret is not created for you)
  - properties: Store credentials in a properties file, which is typically used in Java-related technologies.


....
rhoas serviceaccount reset-credentials [flags]
....

=== Examples

....
# start an interactive prompt to reset credentials
$ rhoas serviceaccount reset-credentials

# reset credentials for the service account specified and save the credentials to a JSON file
$ rhoas serviceaccount reset-credentials --id 173c1ad9-932d-4007-ae0f-4da74f4d2ccd -o json

....

=== Options

....
      --file-format string     Format in which to save the service account credentials. Choose from: "env", "json", "properties", "kubernetes-secret"
      --file-location string   Sets a custom file location to save the credentials.
      --id string              The unique ID of the service account for which you want to reset the credentials.
      --overwrite              Forcibly overwrite a credentials file if it already exists.
  -y, --yes                    Skip confirmation to forcibly reset service account credentials
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_serviceaccount{relfilesuffix}[rhoas serviceaccount]	 - Create, list, describe, delete and update service accounts

