ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-use_{context}']
= rhoas service-registry use

[role="_abstract"]
[beta] Use a Service Registry instance

[discrete]
== Synopsis

 
Select a Service Registry instance to use with all instance-specific commands.
You can specify a Service Registry instance by --name or --id.

When you set the Service Registry instance to be used, it is set as the current instance for all rhoas service-registry artifact commands.

This command is available as part of the Development Preview release.


....
rhoas service-registry use [flags]
....

[discrete]
== Examples

....
# Use a Service Registry instance by name
rhoas service-registry use --name my-service-registry

# Use a Service Registry instance by ID
rhoas service-registry use --id 1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

....

[discrete]
== Options

      `--id` _string_::     Unique ID of the Service Registry instance you want to set as the current instance
      `--name` _string_::   Name the Service Registry instance you want to set as the current instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [beta] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [beta] Service Registry commands
endif::[]

