ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-metadata-set_{context}']
= rhoas service-registry artifact metadata-set

[role="_abstract"]
[beta] Update artifact metadata

[discrete]
== Synopsis

Updates the metadata for an artifact in a Service Registry instance
Editable metadata includes fields like name and description

This command is available as part of the Development Preview release.


....
rhoas service-registry artifact metadata-set [flags]
....

[discrete]
== Examples

....
## Update the metadata for an artifact
rhoas service-registry artifact metadata-set --artifact-id=my-artifact --group=my-group --name=my-name --description=my-description

## Update the metadata for an artifact using your default editor ($EDITOR)
rhoas service-registry artifact metadata-set --artifact-id=my-artifact

##  Update the metadata for an artifact using Visual Studio Code
EDITOR="code -w" rhoas service-registry artifact metadata-set --artifact-id=my-artifact

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
      `--description` _string_::   Custom description of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
      `--name` _string_::          Custom name of the artifact
  `-o`, `--output` _string_::      Output format (json, yaml, yml)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [beta] Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [beta] Manage Service Registry artifacts
endif::[]

