ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-cluster-status_{context}']
= rhoas cluster status

[role="_abstract"]
View the status of the current Kubernetes or OpenShift cluster

[discrete]
== Synopsis

View information about the current Kubernetes or OpenShift cluster. You can use this information to connect your application service to the cluster.

Before using this command, you must be logged in to a Kubernetes or OpenShift cluster. The command uses your kubeconfig file to identify the cluster context.


....
rhoas cluster status [flags]
....

[discrete]
== Examples

....
# print status of the current cluster
$ rhoas cluster status

....

[discrete]
== Options

      `--kubeconfig` _string_::   Location of the kubeconfig file

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_cluster.adoc#rhoas-cluster[rhoas cluster]	 - View and perform operations on your Kubernetes or OpenShift cluster
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-cluster_{context}[rhoas cluster]	 - View and perform operations on your Kubernetes or OpenShift cluster
endif::[]

