docs/commands/-service-registry-artifact-get.adocifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-get_{context}']
= service-registry artifact get

[role="_abstract"]
Get artifact by ID and group

[discrete]
== Synopsis

Get artifact by specifying ID and group.
Command fetches the latest artifact from the registry based on the artifact-id and group.

When --version is specified, the command fetches the specific artifact version.
Get command fetches artifacts based on --group and --artifact-id and --version.
For fetching artifacts using global identifiers, use the "service-registry download" command


....
rhoas service-registry artifact get [flags]
....

[discrete]
== Examples

....
## Get latest artifact with name "my-artifact" and print it out to standard out
rhoas service-registry artifact get --artifact-id=my-artifact

## Get latest artifact with name "my-artifact" from group "my-group" and save it to artifact.json file
rhoas service-registry artifact get --artifact-id=my-artifact --group=my-group --output-file=artifact.json

## Get latest artifact and pipe it to another command
rhoas service-registry artifact get --artifact-id=my-artifact | grep -i 'user'

## Get artifact with custom version and print it out to standard out
rhoas service-registry artifact get --artifact-id=myartifact --version=4

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
      `--output-file` _string_::   Location of the output file
      `--version` _string_::       Version of the artifact

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts
endif::[]

