== rhoas kafka describe

View configuration details of a Kafka instance

=== Synopsis

View configuration fields and their values for a Kafka instance.

Pass the ``–id'' flag to specify which instance you would like to view.

If the ``–id'' flag is not passed then the selected Kafka instance will
be used, if available.

You can view the output as either as JSON or YAML.

....
rhoas kafka describe [flags]
....

=== Examples

....
# view the current Kafka instance instance
$ rhoas kafka describe

# view a specific instance by passing the --id flag
$ rhoas kafka describe --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# customise the output format
$ rhoas kafka describe -o yaml
....

=== Options

....
  -h, --help            help for describe
      --id string       ID of the Kafka instance you want to describe. If not set, the current Kafka instance will be used.
  -o, --output string   Format to display the Kafka instance. Choose from: "json", "yaml", "yml". (default "json")
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_kafka.adoc[rhoas kafka] - Create, view, use and manage your
Kafka instances
