== rhoas serviceaccount reset-credentials

Reset credentials for a service account

=== Synopsis

Generate new SASL/PLAIN credentials for a service account and revoke the
old credentials

....
rhoas serviceaccount reset-credentials [flags]
....

=== Examples

....
$ rhoas serviceaccount reset-credentials --id 173c1ad9-932d-4007-ae0f-4da74f4d2ccd -o json
....

=== Options

....
      --file-location string   Sets a custom file location to save the credentials
  -f, --force                  Forcefully reset credentials for the service account
  -h, --help                   help for reset-credentials
      --id string              The unique ID of the service account to delete
  -o, --output string          Format of the config [env, kafka, properties, json, kube] (default "env")
      --overwrite              Force overwrite a file if it already exists
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_serviceaccount.adoc[rhoas serviceaccount] - Manage your
service accounts

==== Auto generated by spf13/cobra on 14-Jan-2021
