== rhoas serviceaccount create

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Create a service account

=== Synopsis

Create a service account with credentials that are saved to a file.
			
Applications and tools use these service account credentials to authenticate 
and interact with your application services.

You must specify an output format into which the credentials will be stored.
  - env (default): Store credentials in an env file as environment variables
  - json: Store credentials in a JSON file
  - properties: Store credentials in a properties file, which is typically used in Java-related technologies.


....
rhoas serviceaccount create [flags]
....

=== Examples

....
# create a service account through an interactive prompt
$ rhoas serviceaccount create

# create a service account and save the credentials in a JSON file
$ rhoas serviceaccount create --file-format json

# create a service account and forcibly overwrite the credentials file if it exists already
$ rhoas serviceaccount create --overwrite

# create a service account and save credentials to a custom file location
$ rhoas serviceaccount create --file-location=./service-acct-credentials.json

....

=== Options

....
      --description string     Description for the service account. Only alphanumeric characters and '-', '.', ',' are accepted.
      --file-format string     Format in which to save the service account credentials. Choose from: "env", "json", "properties"
      --file-location string   Sets a custom file location to save the credentials.
      --name string            Name of the service account.
      --overwrite              Forcibly overwrite a credentials file if it already exists.
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_serviceaccount{relfilesuffix}[rhoas serviceaccount]	 - Create, list, describe, delete and update service accounts

