== rhoas kafka create

Create a Kafka instance

=== Synopsis

Create a Kafka instance on a particular cloud provider and region.

After creating the Kafka instance you can view it by running ``rhoas
kafka describe''.

....
rhoas kafka create [flags]
....

=== Examples

....
# start an interactive prompt to fill out the configuration values for the instance
$ rhoas kafka create

# create a Kafka instance
$ rhoas kafka create my-kafka-instance

# create a Kafka instance and output the result in YAML
$ rhoas kafka create -o yaml
....

=== Options

....
  -o, --output string     Format in which to display the Kafka instance. Choose from: "json", "yaml", "yml". (default "json")
      --provider string   Cloud provider ID.
      --region string     Cloud provider Region ID.
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_kafka.adoc[rhoas kafka] - Create, view, use, and manage your
Kafka instances
