ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-list_{context}']
= rhoas service-registry list

[role="_abstract"]
List Service Registry instances

[discrete]
== Synopsis

 
List all Service Registry instances for your account with the ability to paginate over the results.


....
rhoas service-registry list [flags]
....

[discrete]
== Examples

....
rhoas service-registry list

....

[discrete]
== Options

      `--limit` _int32_::       The maximum number of Service Registry instances to be returned. (default 100)
  `-o`, `--output` _string_::   Format in which to display the Service Registry instance. Choose from: "json", "yml", "yaml".
      `--page` _int32_::        Display the Service Registry instances from the specified page number. (default 1)
      `--search` _string_::     Text search to filter the Service Registry instances by name.

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]

