ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-acl-admin_{context}']
= rhoas kafka acl admin

[role="_abstract"]
Give admin rights to the account

[discrete]
== Synopsis

This command will give specified account permission to create and delete ACLs in a Kafka instance.

....
rhoas kafka acl admin [flags]
....

[discrete]
== Examples

....
# Give admin rights to user "abc"
$ rhoas kafka acl admin --user abc    

# Give admin rights to a service account
$ rhoas kafka acl admin --service-account srvc-acct-0837725a-4e69-44e1-af3b-29da30aa85ce

# Give admin rights to all accounts for a specific kafka instance
$ rhoas kafka acl admin --all-accounts --instance-id c5hv7iru4an1g84pogp0

....

[discrete]
== Options

      `--all-accounts`::               Set the ACL principal to match all accounts (wildcard). Cannot be used in conjunction with --service-account or --user
      `--service-account` _string_::   Service account client ID to use as principal for this operation
      `--user` _string_::              User ID to be use as principal

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_acl.adoc#rhoas-kafka-acl[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-acl_{context}[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]

