== rhoas kafka create

Create a Kafka instance

=== Synopsis

Create a Kafka instance with custom configuration values, otherwise use
default values.

Configuration options available: name, cloud provider, region.

The created instance can be viewed from the command-line and the web UI.

....
rhoas kafka create [flags]
....

=== Examples

....
# start an interactive prompt to fill out the configuration values for the instance
$ rhoas kafka create

# create a Kafka instance with flags. Optional fields will be populated with default values
$ rhoas kafka create --name "my-kafka-cluster"

# create a Kafka instance and output the result in YAML
$ rhoas kafka create -o yaml
....

=== Options

....
  -h, --help              help for create
  -n, --name string       Name of the Kafka instance
  -o, --output string     Format to display the Kafka instance. Choose from: "json", "yaml", "yml" (default "json")
      --provider string   Cloud provider ID
      --region string     Cloud provider Region ID
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_kafka.adoc[rhoas kafka] - Create, view, use and manage your
Kafka instances
