== rhoas cluster connect

Connect your services to Kubernetes or OpenShift

=== Synopsis

Connect your application services to your Kubernetes or OpenShift
cluster. The kubeconfig file is used to connect to the cluster and
identify the context.

A service account is created and mounted as a secret into your cluster.
This enables you to mount credentials directly to your application.

This command works in two modes:

* If the RHOAS Operator is installed in the cluster, you can use it to
bind your instance automatically.
* Create the secret only. This mode does not require the Operator to be
installed.

You can interactively select the service instance by using the
``–interactive-select'' flag

....
rhoas cluster connect [flags]
....

=== Examples

....
# connect the current Kafka instance to your cluster
$ rhoas cluster connect
....

=== Options

....
      --interactive-select   Interactively select the service instance that will be bound to your Kubernetes or OpenShift cluster.
      --kubeconfig string    Location of the kubeconfig file.
      --secret-name string   Name of the secret that holds the Kafka credentials. (default "kafka-credentials")
      --secret-only          Creates the secret, but doesn't bind the instance. Use this flag if the RHOAS Operator is not installed in the Kubernetes or OpenShift cluster.
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_cluster.adoc[rhoas cluster] - View and perform operations on
your Kubernetes or OpenShift cluster
