ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-consumer-group-list_{context}']
= rhoas kafka consumer-group list

[role="_abstract"]
List all consumer groups

[discrete]
== Synopsis

List all consumer groups in the current Apache Kafka instance.

....
rhoas kafka consumer-group list [flags]
....

[discrete]
== Examples

....
# list all consumer groups
$ rhoas kafka consumer-group list

# list all consumer groups as JSON
$ rhoas kafka consumer-group list -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the consumer groups. Choose from: "json", "yml", "yaml"
      `--page` _int32_::        Current page number for list of consumer groups. (default 1)
      `--search` _string_::     Text search to filter consumer groups by ID
      `--size` _int32_::        Maximum number of consumer groups to be returned per page. (default 10)
      `--topic` _string_::      Fetch the consumer groups for a specific Kafka topic

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_consumer-group.adoc#rhoas-kafka-consumer-group[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance.
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-consumer-group_{context}[rhoas kafka consumer-group]	 - Describe, list, and delete consumer groups for the current Kafka instance.
endif::[]

