ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-describe_{context}']
= rhoas kafka describe

[role="_abstract"]
View configuration details of an Apache Kafka instance

[discrete]
== Synopsis

View configuration fields and their values for an Apache Kafka instance.

Pass the "--id" flag to specify which instance you would like to view.

If the "--id" flag is not passed then the selected Kafka instance will be used, if available.

You can view the output as either as JSON or YAML.


....
rhoas kafka describe [flags]
....

[discrete]
== Examples

....
# view the current Kafka instance instance
$ rhoas kafka describe

# view a specific instance by passing the --id flag
$ rhoas kafka describe --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# view a specific instance by passing the --name flag
$ rhoas kafka describe --name=my-kafka

# customise the output format
$ rhoas kafka describe -o yaml

....

[discrete]
== Options

      `--bootstrapserver`::     If specified, only bootstrap server host of the Kafka instance will be displayed
      `--id` _string_::         Unique ID of the Kafka instance you want to view
      `--name` _string_::       Name of the Kafka instance you want to view
  `-o`, `--output` _string_::   Format in which to display the Kafka instance (choose from: "json", "yml", "yaml") (default "json")

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka.adoc#rhoas-kafka[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]

