ifdef::env-github,env-browser[:context: cmd]
= [[ref-rhoas-service-account-describe_{context}]]rhoas service-account describe

[role="_abstract"]
View configuration details of a service account

[discrete]
== Synopsis

View configuration fields and their values for a service account.

Pass the "--id" flag to specify which service account you would like to view.

You can view the output as either as JSON or YAML.


....
rhoas service-account describe [flags]
....

[discrete]
== Examples

....
# view a specific service account
$ rhoas service-account describe --id=8a06e685-f827-44bc-b0a7-250bc8abe52e --output yml

....

[discrete]
== Options

      `--id` _string_::         The unique ID of the service account to view
  `-o`, `--output` _string_::   Format in which to display the service account. Choose from: "json", "yml", "yaml" (default "json")

[discrete]
== Options inherited from parent commands

  `-d`, `--debug`::   Enable debug mode
  `-h`, `--help`::    Show help for a command

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-account.adoc#user-content-ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]

