ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-create_{context}']
= rhoas service-registry create

[role="_abstract"]
Create a Service Registry instance

[discrete]
== Synopsis

Create a Service Registry instance to store and manage your schema and API artifacts. 


....
rhoas service-registry create [flags]
....

[discrete]
== Examples

....
## Create Service Registry
rhoas service-registry create myregistry

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the Service Registry instance. Choose from: "json", "yml", "yaml". (default "json")
      `--use`::                 Set the new Service Registry instance to the current instance (default true)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]

