== rhoas completion

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Outputs shell completion for the given shell (bash, zsh or fish)

=== Synopsis

Outputs shell completion for the given shell (bash, zsh or fish).

To find what shell you are currently running, run `echo $0`.

Run `rhoas completion [bash|zsh|fish] -h` for instructions on installing completions for your shell.

When you have installed the completion script, make sure you restart your shell for changes to take effect.


....
rhoas completion [flags]
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas{relfilesuffix}[rhoas]	 - RHOAS CLI
* link:rhoas_completion_bash{relfilesuffix}[rhoas completion bash]	 - Generate completion script for Bash shell
* link:rhoas_completion_fish{relfilesuffix}[rhoas completion fish]	 - Generate completion script for fish shell
* link:rhoas_completion_zsh{relfilesuffix}[rhoas completion zsh]	 - Generate completion script for Zsh shell

