ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-download_{context}']
= rhoas service-registry artifact download

[role="_abstract"]
[alpha] Download artifacts from Service Registry using global identifiers

[discrete]
== Synopsis

Get single or more artifacts by group, content, hash or globalIds.
NOTE: Use "service-registry get" command to download artifacts by artifactId.

Flags are used to specify the artifact to download:

--contentId - ID if the content is from metadata
--globalId - globalId of the content from metadata
--hash - SHA-256 hash of the content

This command is available as part of the Development Preview release.


....
rhoas service-registry artifact download [flags]
....

[discrete]
== Examples

....
## Get latest artifact by content ID
rhoas service-registry artifact download --content-id=183282932983

## Get latest artifact by content ID to specific file
rhoas service-registry artifact download --content-id=183282932983 --output-file=schema.json

## Get latest artifact by global ID
rhoas service-registry artifact download --global-id=383282932983

## Get latest artifact by hash
rhoas service-registry artifact download --hash=c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4

....

[discrete]
== Options

      `--content-id` _int_::       ContentId of the artifact (default -1)
      `--global-id` _int_::        Global ID of the artifact (default -1)
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--hash` _string_::          SHA-256 hash of the artifact
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
      `--output-file` _string_::   Location of the output file

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]

