== rhoas

RHOAS CLI

=== Synopsis

Manage your application services directly from the command-line.

=== Examples

....
# authenticate securely through your web browser
$ rhoas login

# create a Kafka instance
$ rhoas kafka create --name "my-kafka-cluster"

# create a service account and save credentials to a JSON file
$ rhoas serviceaccount create -o json

# connect your Kubernetes/OpenShift cluster to a service
$ rhoas cluster connect
....

=== Options

....
  -d, --debug   Enable debug mode
  -h, --help    help for rhoas
....

=== SEE ALSO

* link:rhoas_cluster.adoc[rhoas cluster] - View and perform operations on
your Kubernetes or OpenShift Cluster
* link:rhoas_completion.adoc[rhoas completion] - Generate completion
script
* link:rhoas_kafka.adoc[rhoas kafka] - Manage your Kafka instances
* link:rhoas_login.adoc[rhoas login] - Log in to RHOAS.
* link:rhoas_logout.adoc[rhoas logout] - Log out from RHOAS
* link:rhoas_serviceaccount.adoc[rhoas serviceaccount] - Create, list,
delete and update service accounts

