ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-metadata-get_{context}']
= rhoas service-registry artifact metadata-get

[role="_abstract"]
[alpha] Get artifact metadata

[discrete]
== Synopsis

Gets the metadata for an artifact in a Service Registry instance
The returned metadata includes both generated (read-only) and editable metadata (such as name and description).

This command is available as part of the developer preview


....
rhoas service-registry artifact metadata-get [flags]
....

[discrete]
== Examples

....
## Get latest artifact metadata for default group
rhoas service-registry artifact metadata --artifact-id=my-artifact

## Get latest artifact metadata for my-group group
rhoas service-registry artifact metadata --artifact-id=my-artifact --group mygroup

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
  `-o`, `--output` _string_::      Output format (json, yaml, yml)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]

