== rhoas kafka list

List all Kafka instances

=== Synopsis

List all Kafka instances in your organization.

This command will provide a high level view of all Kafka instances in
your organization. The fields displayed are: ID, Name, Owner, Status,
Cloud Provider, Region. Use the describe command to view all fields for
a specific instance.

The instances are displayed by default in a table, but can also be
displayed as JSON or YAML.

....
rhoas kafka list [flags]
....

=== Examples

....
# list all Kafka instances using the default (plain) output format
$ rhoas kafka list

# list all Kafka instances using JSON as the output format
$ rhoas kafka list -o json
....

=== Options

....
  -h, --help            help for list
      --limit int       Limit of items that should be returned from server (default 100)
  -o, --output string   Output format of the results. Choose from ["plain" "json" "yml" "yaml"] (default "plain")
      --page int        Page that should be returned from server
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_kafka.adoc[rhoas kafka] - Manage your Kafka instances

