== rhoas serviceaccount describe

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

View configuration details of a service account

=== Synopsis

View configuration fields and their values for a service account.

Pass the "--id" flag to specify which service account you would like to view.

You can view the output as either as JSON or YAML.


....
rhoas serviceaccount describe [flags]
....

=== Examples

....
# view a specific service account
$ rhoas describe --id=8a06e685-f827-44bc-b0a7-250bc8abe52e --output yml

....

=== Options

....
      --id string       The unique ID of the service account to view
  -o, --output string   Format in which to display the service account. Choose from: "json", "yml", "yaml" (default "json")
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_serviceaccount{relfilesuffix}[rhoas serviceaccount]	 - Create, list, describe, delete and update service accounts

