ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-delete_{context}']
= rhoas kafka delete

[role="_abstract"]
Delete an Apache Kafka instance

[discrete]
== Synopsis

Permanently delete an Apache Kafka instance, including all topics.

When this command is run, you will be asked to confirm the name of the instance you want to delete.
Otherwise you can pass "--yes" to skip confirmation and forcibly delete the instance.


....
rhoas kafka delete [flags]
....

[discrete]
== Examples

....
# delete the current Kafka instance
$ rhoas kafka delete

# delete a Kafka instance with a specific ID
$ rhoas kafka delete --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# delete a Kafka instance with a specific name
$ rhoas kafka delete --name=my-kafka

....

[discrete]
== Options

      `--id` _string_::     Unique ID of the Kafka instance you want to delete
      `--name` _string_::   Name of the Kafka instance you want to delete
  `-y`, `--yes`::           Skip confirmation to forcibly delete this Kafka instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka.adoc#rhoas-kafka[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]

