ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-acl-delete_{context}']
= rhoas kafka acl delete

[role="_abstract"]
List all Kafka ACL rules.

[discrete]
== Synopsis

This command will display list of Kafka ACL rules

The instances are displayed by default in a table, but can also be displayed as JSON or YAML.


....
rhoas kafka acl delete [flags]
....

[discrete]
== Examples

....
# Display Kafka ACL rules for the instance
$ rhoas kafka acl list

....

[discrete]
== Options

      `--group` _string_::              Consumer group ID
      `--operation` _string_::          ACL operation. Choose from: "create", "alter", "describe-config", "all", "any", "write", "read", "describe", "alter-configs" (default "any")
  `-o`, `--output` _string_::           Specify the output format. Choose from: "json", "yaml", "yml"
      `--pattern-type` _string_::       Determine the pattern type of the ACL resource
      `--permission` _string_::         ACL permission. Choose from: "any", "allow", "deny" (default "any")
      `--resource-type` _string_::      ACL resource type. Choose from: "any", "cluster", "topic", "group", "transactional-id" (default "any")
      `--service-account` _string_::    Service account principal for this operation
      `--topic` _string_::              Topic name
      `--transactional-id` _string_::   Transactional ID
      `--user` _string_::               User account principal for this operation

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_acl.adoc#rhoas-kafka-acl[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-acl_{context}[rhoas kafka acl]	 - Kafka ACL management for users and service accounts
endif::[]

