== rhoas

RHOAS CLI

=== Synopsis

Manage your application services directly from the command line.

=== Examples

....
# authenticate securely through your web browser
$ rhoas login

# create a Kafka instance
$ rhoas kafka create my-kafka-cluster

# create a service account and save credentials to a JSON file
$ rhoas serviceaccount create -o json

# connect your Kubernetes/OpenShift cluster to a service
$ rhoas cluster connect
....

=== Options

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_cluster.adoc[rhoas cluster] - View and perform operations on
your Kubernetes or OpenShift cluster
* link:rhoas_completion.adoc[rhoas completion] - Generate completion
script
* link:rhoas_kafka.adoc[rhoas kafka] - Create, view, use, and manage your
Apache Kafka instances
* link:rhoas_login.adoc[rhoas login] - Log in to RHOAS
* link:rhoas_logout.adoc[rhoas logout] - Log out from RHOAS
* link:rhoas_serviceaccount.adoc[rhoas serviceaccount] - Create, list,
delete and update service accounts
* link:rhoas_status.adoc[rhoas status] - View the status of all currently
used services
* link:rhoas_whoami.adoc[rhoas whoami] - Print current username
