== rhoas kafka connect

connect currently selected Kafka to your OpenShift cluster

=== Synopsis

Connect will create secret containing Kafka credentials.

Connect command will use current Kubernetes context (namespace/project
you have selected) created by oc or kubectl command line. Connect
command will retrieve credentials for your kafka and mount them as
secret into your project. You can use secret directly or utilize
service-binding-operator to automatically bind your instance For more
details please visit:

https://github.com/bf2fc6cc711aee1a0c2a/operator

If your cluster has binding-operator installed you would be able to bind
your application with credentials directly from the console etc.

....
rhoas kafka connect [flags]
....

=== Options

....
      --forceKafkaSelection                Name of the secret that will be used to hold Kafka credentials
  -h, --help                               help for connect
      --kubeconfig string                  Location of the .kube/config file
  -l, --local-only oc apply -f kafka.yml   Provide yaml file containing changes without applying them to the cluster. Developers can use oc apply -f kafka.yml to apply it manually
  -s, --secret-only                        Apply only secret and without CR. Can be used when no binding operator is configured
      --secretName string                  Name of the secret that will be used to hold Kafka credentials (default "kafka-credentials")
....

=== SEE ALSO

* link:rhoas_kafka.md[rhoas kafka] - Manage your Kafka clusters

==== Auto generated by spf13/cobra on 2-Dec-2020
