ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-import_{context}']
= rhoas service-registry artifact import

[role="_abstract"]
[alpha] Import data into a Service Registry instance

[discrete]
== Synopsis

Import all artifacts and metadata from export file to another Service Segistry instance

This command is available as part of the developer preview


....
rhoas service-registry artifact import [flags]
....

[discrete]
== Examples

....
## Import all artifacts and metadata from export file to another Service Registry instance
rhoas service-registry artifact import --file=export.zip

....

[discrete]
== Options

      `--file` _string_::          File location of the artifact
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]

