ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-create_{context}']
= rhoas kafka create

[role="_abstract"]
Create an Apache Kafka instance

[discrete]
== Synopsis

Create an Apache Kafka instance on a particular cloud provider and region.

After creating the instance you can view it by running "rhoas kafka describe".


....
rhoas kafka create [flags]
....

[discrete]
== Examples

....
# start an interactive prompt to fill out the configuration values for the instance
$ rhoas kafka create

# create a Kafka instance
$ rhoas kafka create my-kafka-instance

# create a Kafka instance and output the result in YAML
$ rhoas kafka create -o yaml

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the Kafka instance (choose from: "json", "yml", "yaml") (default "json")
      `--provider` _string_::   Cloud Provider ID
      `--region` _string_::     Cloud Provider Region ID
      `--use`::                 Set the new Kafka instance to the current instance (default true)
  `-w`, `--wait`::              Wait for the Kafka instance to finish creating

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka.adoc#rhoas-kafka[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka_{context}[rhoas kafka]	 - Create, view, use, and manage your Kafka instances
endif::[]

