ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-delete_{context}']
= rhoas service-registry artifact delete

[role="_abstract"]
[alpha] Deletes single or all artifacts in a given group

[discrete]
== Synopsis

Deletes single or all artifacts in a given group.

When called without arguments, deletes all artifacts in the group
When --artifact-id is specified, deletes only a single artifact and its version
When --group parameter is missing, the command uses the "default" group.

This command is available as part of the developer preview


....
rhoas service-registry artifact delete [flags]
....

[discrete]
== Examples

....
## Delete all artifacts in the group "default"
rhoas service-registry artifact delete

## Delete artifact in the group "default" with name "my-artifact"
rhoas service-registry artifact delete --artifact-id=my-artifact

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
  `-y`, `--yes`::                  Delete artifact without prompt

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - [alpha] Manage Service Registry artifacts
endif::[]

