ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-account-create_{context}']
= rhoas service-account create

[role="_abstract"]
Create a service account

[discrete]
== Synopsis

Create a service account with credentials that are saved to a file.
			
Applications and tools use these service account credentials to authenticate 
and interact with your application services.

You must specify an output format into which the credentials will be stored.
  - env (default): Store credentials in an env file as environment variables
  - json: Store credentials in a JSON file
  - properties: Store credentials in a properties file, which is typically used in Java-related technologies.


....
rhoas service-account create [flags]
....

[discrete]
== Examples

....
# create a service account through an interactive prompt
$ rhoas service-account create

# create a service account and save the credentials in a JSON file
$ rhoas service-account create --file-format json

# create a service account and forcibly overwrite the credentials file if it exists already
$ rhoas service-account create --overwrite

# create a service account and save credentials to a custom file location
$ rhoas service-account create --file-location=./service-acct-credentials.json

....

[discrete]
== Options

      `--description` _string_::     Description for the service account (only alphanumeric characters and '-', '.', ',' are valid)
      `--file-format` _string_::     Format in which to save the service account credentials (choose from: "env", "json", "properties")
      `--file-location` _string_::   Sets a custom file location to save the credentials
      `--name` _string_::            Name of the service account
      `--overwrite`::                Forcibly overwrite a credentials file if it already exists

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-account.adoc#rhoas-service-account[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]

