== rhoas cluster connect

connect currently selected Kafka to your OpenShift cluster

=== Synopsis

Connect command links your own OpenShift cluster with Managed Services.

Connect command will use current Kubernetes context (namespace/project
you have selected) created by oc or kubectl command line. Command will
create new service account and mount it as secret into your cluster,
giving you ability to mount credentials directly to your application.

Command work in two modes:

[arabic]
. Using RHOAS operator installed on cluster. You can or utilize
service-binding-operator to automatically bind your instance. For more
details please visit: https://github.com/bf2fc6cc711aee1a0c2a/operator
. Secret only (–secret-only) creates only secret (no extra operator
installation is required)

Using –forceSelect will ignore current command context make interactive
prompt for selecting service instance you want to use.

....
rhoas cluster connect [flags]
....

=== Options

....
  -h, --help                 help for connect
      --kubeconfig string    Location of the .kube/config file
      --secret-name string   Name of the secret that will be used to hold Kafka credentials (default "kafka-credentials")
      --secret-only          Apply only secret and without CR. Can be used without installing RHOAS operator on cluster
      --skip-context         Allows to select services before performing binding
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_cluster.adoc[rhoas cluster] - Managed your services in
OpenShift Cluster

