= rhoas cluster bind

[role="_abstract"]
ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Connect your RHOAS services to Kubernetes or OpenShift applications

[discrete]
== Synopsis

Command allows you to connect services created by connect command to your application
running on OpenShift or Kubernetes platform.
Bind will scan your namespace and detect all application deployments that you can connect your
services with.

Bind command detects Kubernetes deployments and inject managed services credentials to them.
For information about what credentials are injected please refer to individual services
Command will inject credentials as files into `/bindings` folder inside your application.

Bind command will create volume inside your deployment or
ServiceBindingOperator resource if you have it installed on your cluster


....
rhoas cluster bind [flags]
....

[discrete]
== Examples

....
# Bind using interactive mode
$ rhoas cluster bind

# Bind to specific namespace and application
$ rhoas cluster bind --namespace=ns --app-name=myapp

....

=== Options

      --app-name:: string       Name of the kubernetes deployment to bind
      --binding-name:: string   Name of the Service binding object to create when using operator
      --force-operator::        Use ServiceBindingOperator only and fail if Operator is not installed
      --force-sdk::             Use Service Binding SDK and skip ServiceBindingOperator even if installed on the cluster
      --ignore-context::        Ignore currently selected services and ask to select each service separately
      --kubeconfig:: string     Location of the kubeconfig file.
  -n, --namespace:: string      Custom Kubernetes namespace (if not set current namespace will be used)
  -y, --yes::                   Forcibly create a binding without confirmation.

=== Options inherited from parent commands

  -d, --debug::   Enable debug mode
  -h, --help::    Show help for a command

[discrete]
== See Also

* link:rhoas_cluster{relfilesuffix}[rhoas cluster]	 - View and perform operations on your Kubernetes or OpenShift cluster

