== rhoas cluster connect

Connect your services to a Kubernetes or OpenShift

=== Synopsis

Connect your services to your Kubernetes or OpenShift cluster. The
kubeconfig file is used to connect with the cluster and identify the
context.

A service account is created and mounted as a secret into your cluster.
This gives you the ability to mount credentials directly to your
application.

Command work in two modes:

[arabic]
. Using RHOAS operator installed on cluster. You can or utilize
service-binding-operator to automatically bind your instance. For more
details please visit: https://github.com/bf2fc6cc711aee1a0c2a/operator
. Secret only (–secret-only) creates only secret (no extra operator
installation is required)

Using –interactive-select will ignore current command context make
interactive prompt for selecting service instance you want to use.

....
rhoas cluster connect [flags]
....

=== Examples

....
# connect the current Kafka instance to your cluster
$ rhoas cluster connect
....

=== Options

....
  -h, --help                 help for connect
      --interactive-select   Allows to select services before performing binding
      --kubeconfig string    Location of the .kube/config file
      --secret-name string   Name of the secret that will be used to hold Kafka credentials (default "kafka-credentials")
      --secret-only          Apply only secret and without CR. Can be used without installing RHOAS operator on cluster
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_cluster.adoc[rhoas cluster] - View and perform operations on
your Kubernetes or OpenShift Cluster
