ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-artifact-versions_{context}']
= service-registry artifact versions

[role="_abstract"]
Get latest artifact versions by artifact-id and group

[discrete]
== Synopsis

Get latest artifact versions by specifying group and artifact-id

....
rhoas service-registry artifact versions [flags]
....

[discrete]
== Examples

....
## Get latest artifact versions for default group
rhoas service-registry artifact versions --artifact-id=my-artifact

## Get latest artifact versions for my-group group
rhoas service-registry artifact versions --artifact-id=my-artifact --group mygroup

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
  `-o`, `--output` _string_::      Output format (json, yaml, yml)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts
endif::[]

