ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-describe_{context}']
= rhoas service-registry describe

[role="_abstract"]
[alpha] Describe a Service Registry instance

[discrete]
== Synopsis

 
Describe a Service Registry instance. Fetch all required fields including the registry URL. 

This command is available as part of the Development Preview release.


....
rhoas service-registry describe [flags]
....

[discrete]
== Examples

....
# Describe a Service Registry instance by name
rhoas service-registry describe --name <name>


# Describe a Service Registry instance by ID
rhoas service-registry describe --id <id>

....

[discrete]
== Options

      `--id` _string_::         Unique ID of the Service Registry instance (if not provided, the current Service Registry instance will be used)
      `--name` _string_::       Name of the Service Registry instance to view
  `-o`, `--output` _string_::   Format in which to display the Service Registry instance (choose from: "json", "yml", "yaml") (default "json")

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [alpha] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [alpha] Service Registry commands
endif::[]

