ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-account-list_{context}']
= rhoas service-account list

[role="_abstract"]
List service accounts

[discrete]
== Synopsis

List all service accounts.

This command will provide a high level view of all service accounts.

The service accounts are displayed by default in a table, but can also be
displayed as JSON or YAML.


....
rhoas service-account list [flags]
....

[discrete]
== Examples

....
# list all Kafka instances using the default output format
$ rhoas kafka list

# list all Kafka instances using JSON as the output format
$ rhoas kafka list -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Choose a format from: "json", "yml", "yaml", to display the service accounts

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-account.adoc#rhoas-service-account[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]

