== rhoas registry delete

ifdef::env-github,env-browser[:relfilesuffix: .adoc]

Delete an Apache Kafka instance

=== Synopsis

Permanently delete an Apache Kafka instance, including all topics.

When this command is run, you will be asked to confirm the name of the instance you want to delete.
Otherwise you can pass "--yes" to skip confirmation and forcibly delete the instance.


....
rhoas registry delete [flags]
....

=== Examples

....
# delete the current Kafka instance
$ rhoas kafka delete

# delete a Kafka instance with a specific ID
$ rhoas kafka delete --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

....

=== Options

....
      --id string   Unique ID of the Kafka instance you want to delete. If not set, the current Kafka instance will be used.
  -y, --yes         Skip confirmation to forcibly delete this Kafka instance.
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
  -h, --help    Show help for a command
....

=== SEE ALSO

* link:rhoas_registry{relfilesuffix}[rhoas registry]	 - Service Registry commands

