ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-delete_{context}']
= rhoas service-registry delete

[role="_abstract"]
Delete a Service Registry instance

[discrete]
== Synopsis

 
Delete a Service Registry instance along with all of its schema and API artifacts.


....
rhoas service-registry delete [flags]
....

[discrete]
== Examples

....
rhoas service-registry delete <id>

....

[discrete]
== Options

      `--id` _string_::   Unique ID of the Service Registry instance you want to delete. If not set, the current Service Registry instance is used.
  `-y`, `--yes`::         Skip confirmation to forcibly delete this Service Registry instance.

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]

