ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-describe_{context}']
= rhoas service-registry describe

[role="_abstract"]
Describe a Service Registry instance

[discrete]
== Synopsis

 
Describe a Service Registry instance. Fetch all required fields including the registry URL. 


....
rhoas service-registry describe [flags]
....

[discrete]
== Examples

....
rhoas service-registry describe <id>

....

[discrete]
== Options

      `--id` _string_::         Unique ID of the Service Registry instance you want to delete. If not set, the current Service Registry instance is used.
  `-o`, `--output` _string_::   Format in which to display the Service Registry instance. Choose from: "json", "yml", "yaml". (default "json")

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]

