ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-service-registry-use_{context}']
= rhoas service-registry use

[role="_abstract"]
Use a Service Registry instance

[discrete]
== Synopsis

 
Select a Service Registry instance to use with all instance-specific commands.


....
rhoas service-registry use [flags]
....

[discrete]
== Examples

....
rhoas service-registry use <id>

....

[discrete]
== Options

      `--id` _string_::   Unique ID of the Service Registry instance you want to set as the current instance.

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode
      `--version`::     Show rhoas version

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - [Preview] Service Registry commands
endif::[]

