== rhoas kafka describe

View all configuration values of a Kafka instance

=== Synopsis

View all configuration fields and their values for a Kafka instance.

Pass the –id flag to specify which instance you would like to view.

If the –id flag is not passed then the selected Kafka instance will be
used, if available.

The result can be output either as JSON or YAML.

....
rhoas kafka describe [flags]
....

=== Examples

....
# view the currently selected instance
$ rhoas kafka describe

# view a specific instance by passing the --id flag
$ rhoas kafka describe --id=1iSY6RQ3JKI8Q0OTmjQFd3ocFRg

# customise the output format
$ rhoas kafka describe -o yaml
....

=== Options

....
  -h, --help            help for describe
      --id string       ID of the Kafka instance you want to describe. If not set, the currently selected Kafka instance will be used
  -o, --output string   Format to display the Kafka instance. Choose from: "json", "yaml", "yml" (default "json")
....

=== Options inherited from parent commands

....
  -d, --debug   Enable debug mode
....

=== SEE ALSO

* link:rhoas_kafka.adoc[rhoas kafka] - Manage your Kafka instances

