ifdef::env-github,env-browser[:context: cmd]
[id='ref-rhoas-kafka-topic-update_{context}']
= rhoas kafka topic update

[role="_abstract"]
Update a Kafka topic

[discrete]
== Synopsis

Update a topic in the current Apache Kafka instance.


....
rhoas kafka topic update [flags]
....

[discrete]
== Examples

....
# update the message retention period for a topic
$ rhoas kafka topic update --name topic-1 --retention-ms -1

....

[discrete]
== Options

      `--cleanup-policy` _string_::    Determines whether log messages are deleted, compacted, or both
      `--name` _string_::              Topic name
  `-o`, `--output` _string_::          Format in which to display the Kafka topic (choose from: "json", "yml", "yaml")
      `--partitions` _string_::        The number of partitions in the topic
      `--retention-bytes` _string_::   The maximum total size of a partition log segments before old log segments are deleted to free up space
      `--retention-ms` _string_::      The period of time in milliseconds the broker will retain a partition log before deleting it

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_kafka_topic.adoc#rhoas-kafka-topic[rhoas kafka topic]	 - Create, describe, update, list and delete topics
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-kafka-topic_{context}[rhoas kafka topic]	 - Create, describe, update, list and delete topics
endif::[]

