ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-account_list_{context}']
= service-account_list

[role="_abstract"]
List service accounts

[discrete]
== Synopsis

List all service accounts.

This command will provide a high level view of all service accounts.

The service accounts are displayed by default in a table, but can also be
displayed as JSON or YAML.


....
rhoas service-account list [flags]
....

[discrete]
== Examples

....
# list all service accounts using the default output format
$ rhoas service-account list

# list all service accounts using JSON as the output format
$ rhoas service-account list -o json

....

[discrete]
== Options

  `-o`, `--output` _string_::   Format in which to display the service accounts (choose from: "json", "yml", "yaml")

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-account.adoc#rhoas-service-account[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete and update service accounts
endif::[]

