ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-list_{context}']
= service-registry list

[role="_abstract"]
List Service Registry instances

[discrete]
== Synopsis

 
List all Service Registry instances for your account and paginate over the results.


....
rhoas service-registry list [flags]
....

[discrete]
== Examples

....
rhoas service-registry list

....

[discrete]
== Options

      `--limit` _int32_::       The maximum number of Service Registry instances to be returned (default 100)
  `-o`, `--output` _string_::   Format in which to display the Service Registry instance (choose from: "json", "yml", "yaml")
      `--page` _int32_::        Display the Service Registry instances from the specified page number (default 1)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry.adoc#rhoas-service-registry[rhoas service-registry]	 - Service Registry commands
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry_{context}[rhoas service-registry]	 - Service Registry commands
endif::[]

