ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-registry-artifact-create_{context}']
= service-registry artifact create

[role="_abstract"]
Creates new artifact from file or standard input

[discrete]
== Synopsis

Creates a new artifact by posting the artifact content to the registry instance.

Artifacts are typically in JSON format for most of the supported types, but may be in another format for a few (for example, PROTOBUF).
Service Registry attempts to figure out what kind of artifact is being added from the following supported list:

- Avro (AVRO)
- Protobuf (PROTOBUF)
- JSON Schema (JSON)
- Kafka Connect (KCONNECT)
- OpenAPI (OPENAPI)
- AsyncAPI (ASYNCAPI)
- GraphQL (GRAPHQL)
- Web Services Description Language (WSDL)
- XML Schema (XSD)

An artifact is created using the content provided in the request body.
This content is created with a unique artifact ID that can be provided by user.
If not provided in the request, the registry server generates a unique ID for the artifact.
It is typically recommended that callers provide the ID, because this is a meaningful identifier, and for most use cases should be supplied by the caller.
If an artifact with the provided artifact ID already exists, the command will fail with an error.

When the --group parameter is missing, the command uses the "default" group.
when the --instance-id is missing, the command creates a new artifact for the currently active Service Registry instance (displayed in rhoas service-registry describe)


....
rhoas service-registry artifact create [flags]
....

[discrete]
== Examples

....
# Create an artifact in the default group
rhoas service-registry artifact create my-artifact.json

# Create an artifact with the specified type
rhoas service-registry artifact create --type=JSON my-artifact.json

....

[discrete]
== Options

      `--artifact-id` _string_::   ID of the artifact
      `--description` _string_::   Custom description of the artifact
      `--file` _string_::          File location of the artifact
  `-g`, `--group` _string_::       Artifact group (default "default")
      `--instance-id` _string_::   ID of the Service Registry instance to be used. By default, uses the currently selected instance
      `--name` _string_::          Custom name of the artifact
  `-o`, `--output` _string_::      Output format (json, yaml, yml) (default "json")
  `-t`, `--type` _string_::        Type of artifact. Choose from: AVRO, PROTOBUF, JSON, OPENAPI, ASYNCAPI, GRAPHQL, KCONNECT, WSDL, XSD, XML
      `--version` _string_::       Custom version of the artifact (for example 1.0.0)

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-registry_artifact.adoc#rhoas-service-registry-artifact[rhoas service-registry artifact]	 - Manage Service Registry artifacts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-registry-artifact_{context}[rhoas service-registry artifact]	 - Manage Service Registry artifacts
endif::[]

