ifdef::env-github,env-browser[:context: cmd]
[id='ref-service-account-reset-credentials_{context}']
= service-account reset-credentials

[role="_abstract"]
Reset service account credentials

[discrete]
== Synopsis

Reset the credentials for a service account.

This command generates a new password for a service account. After the credentials have been reset, any applications or tools that use the credentials must be updated to use the new password.

You must specify an output format into which the credentials will be stored.

- env (default): Store credentials in an env file as environment variables
- json: Store credentials in a JSON file
- properties: Store credentials in a properties file, which is typically used in Java-related technologies.


....
rhoas service-account reset-credentials [flags]
....

[discrete]
== Examples

....
# Start an interactive prompt to reset credentials
$ rhoas service-account reset-credentials

# Reset credentials for the service account specified and save the credentials to a JSON file
$ rhoas service-account reset-credentials --id 173c1ad9-932d-4007-ae0f-4da74f4d2ccd -o json

....

[discrete]
== Options

      `--file-format` _string_::   Format in which to save the service account credentials (choose from: "env", "json", "properties")
      `--id` _string_::            The unique ID of the service account for which you want to reset the credentials
      `--output-file` _string_::   Sets a custom file location to save the credentials
      `--overwrite`::              Forcibly overwrite a credentials file if it already exists
  `-y`, `--yes`::                  Skip confirmation to forcibly reset service account credentials

[discrete]
== Options inherited from parent commands

  `-h`, `--help`::      Show help for a command
  `-v`, `--verbose`::   Enable verbose mode

[discrete]
== See also


ifdef::env-github,env-browser[]
* link:rhoas_service-account.adoc#rhoas-service-account[rhoas service-account]	 - Create, list, describe, delete, and update service accounts
endif::[]
ifdef::pantheonenv[]
* link:{path}#ref-rhoas-service-account_{context}[rhoas service-account]	 - Create, list, describe, delete, and update service accounts
endif::[]

