[id="proc-configuring-rhoas_{context}"]
= Configuring rhoas

[role="_abstract"]
After you install the `rhoas` CLI,
you can enable command completion to automatically complete `rhoas` commands or suggest options when you press *Tab*.

NOTE: The procedure for enabling command completion depends on the shell you are using.
To determine which shell you are using, run the `echo $0` command.

ifdef::enterprise[]
You can enable command completion for each of the following shells:

* xref:_enabling_command_completion_on_bash[Bash]
* xref:_enabling_command_completion_on_zsh[Zsh]
* xref:_enabling_command_completion_on_fish[Fish]
endif::[]

.Prerequisites

ifndef::enterprise[]
* You must have link:getting-started.adoc[installed the `rhoas` CLI].
endif::[]
ifdef::enterprise[]
* You must have xref:proc-installing-rhoas_{context}[installed the `rhoas` CLI].
endif::[]

== Enabling command completion on Bash

.Procedure

. Create the `rhoas_completions` script file.
+
[source,shell]
----
$ rhoas completion bash > rhoas_completions
----

. Move the script file to a special Bash completions directory.
+
--
.Linux
[source,shell]
----
$ sudo mv rhoas_completions /etc/bash_completion.d/rhoas
----

.macOS
[source,shell]
----
$ sudo mv rhoas_completions /usr/local/etc/bash_completion.d/rhoas
----
--

. Open a new terminal window.
+
Command completion is enabled.

== Enabling command completion on Zsh

.Procedure

. Install the command completion script.
+
[source,shell]
----
$ rhoas completion zsh > "${fpath[1]}/_rhoas"
----

. Unless already installed, enable command completions.
+
[source,shell]
----
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
----

. Open a new terminal window.
+
Command completion is enabled.

== Enabling command completion on Fish

.Procedure

. Install fish completions.
+
[source,shell]
----
$ rhoas completion -s fish > ~/.config/fish/completion/gh.fish
----

. Open a new terminal window.
+
Command completion is enabled.

ifndef::enterprise[]
== Next steps

link:logging-in.adoc[Logging in]
endif::[]
