=== Configuring the CLI

==== Enabling tab completion

After you install the `rhoas` CLI, you can enable tab completion to automatically complete `rhoas` commands or suggest options when you pres Tab.

===== Prerequisites
* You must have link:getting-started.adoc[installed the `rhoas` CLI].

===== Linux

The following steps enable tab completion for Bash.

1. Save the Bash completion code to a file.
+
[source,shell]
----
rhoas completion bash > rhoas_bash_completion
----

2. Copy the file to `/etc/bash_completion.d/`.
+
[source,shell]
----
sudo cp rhoas_bash_completion /etc/bash_completion.d
----
+ 
You can also save the file to a local directory and source it from your `.bashrc` file instead.

===== macOS

The following steps enable tab completion for Bash.

1. Save the Bash completion code to a file.
+
[source,shell]
----
rhoas completion bash > rhoas_bash_completion
----

2. Copy the file to `/etc/bash_completion.d/`.
+
[source,shell]
----
sudo cp rhoas_bash_completion /usr/local/etc/bash_completion.d/
----
+ 
You can also save the file to a local directory and source it from your `.bashrc` file instead.

Tab completion is enabled when you open a new terminal.