=== Installing rhoas

The following section describes how to install `rhoas` on different platforms.

NOTE: In the following guides replace `VERSION` with the release version of the CLI.

==== Installing rhoas on Linux and macOS

1. To install the latest release of `rhoas`, you can run the following script:
+
[source,shell]
----
curl -o- https://raw.githubusercontent.com/bf3fc6c/cli/main/scripts/install.sh | bash
----
+ 
CAUTION: Always inspect a script before running it.
+
You can install a specific version of the CLI to install by passing an argument:
+
[source,shell]
----
curl -o- https://raw.githubusercontent.com/bf3fc6c/cli/main/scripts/install.sh | bash -s $VERSION
----
+
NOTE: On Linux, `rhoas` will be installed to `$HOME/.local/bin`, and on macOS it will be installed to `$HOME/bin`. These should already be on your `PATH`, but if not please add them so that you can run `rhoas` from any directory.

2. The CLI is now installed! To verify this, run a command:
+
[source,shell]
----
$ rhoas --version
rhoas version <latest-version>
----

==== Installing rhoas on Fedora

You can install the RPM on Fedora using DNF:

[source,shell]
----
sudo dnf install -y https://github.com/bf3fc6c/cli/releases/download/${VERSION}/rhoas_${VERSION}_linux_amd64.rpm
----

The CLI is now installed and ready to use. To verify this, run a command:

[source,shell]
----
$ rhoas --version
rhoas version ${VERSION}
----

==== Installing rhoas on RHEL and Centos

You can install the RPM on RHEL and CentOS using Yum:

[source,shell]
----
sudo yum install -y https://github.com/bf3fc6c/cli/releases/download/${VERSION}/rhoas_${VERSION}_linux_amd64.rpm
----

The CLI is now installed and ready to use. To verify this, run a command:

[source,shell]
----
$ rhoas --version
rhoas version ${VERSION}
----

==== Installing rhoas on Windows

1. Download the latest Windows Zip release from link:https://github.com/bf3fc6c/cli/releases[Releases].
2. Create a folder at `C:\rhoas`.
3. Extract the `rhoas.exe` file from the Zip folder.
4. Move the `rhoas.exe` file to `C:\rhoas`.

==== Setting the `PATH` variable for Windows 10

1. Click **Search** and type `env` or `environment`.
2. Select **Edit environment variables for your account**.
3. Select **Path** from the **Variable** section and click **Edit**.
4. Click **New** and type `C:\rhoas` into the field or click **Browse** and select the directory, and click **OK**.

==== Next steps

link:configuring-the-cli.adoc[Configuring the CLI]
