[id="proc-installing-rhoas_{context}"]
= Installing rhoas

[role="_abstract"]
You can install `rhoas` on Linux, macOS, or Windows.

== Installing rhoas on Linux

If you are using Linux, you can install `rhoas` by either using the installation script, or the RPM.

=== Installation script

.Procedure

. Review the `install.sh` installation script.
+
The script is located at https://github.com/bf3fc6c/cli/blob/main/scripts/install.sh.

. Run the `install.sh` script:
+
--
[source,shell]
----
$ curl -o- https://raw.githubusercontent.com/bf3fc6c/cli/main/scripts/install.sh | bash
----

[NOTE]
====
You can use the `-s` argument to install a specific version of the `rhoas` CLI. For example, this command installs version `0.19.0`:

[source,shell]
----
$ curl -o- https://raw.githubusercontent.com/bf3fc6c/cli/main/scripts/install.sh | bash -s 0.19.0
----
====

The `rhoas` CLI is installed in `$HOME/.local/bin`.
--

. Verify that the `rhoas` installation directory is on your `$PATH`.
+
--
To check your `$PATH`, run the following command:

[source,shell]
----
$ echo $PATH
----
--

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` 0.19.0 is installed:

[source,shell]
----
$ rhoas --version
rhoas version 0.19.0
----
--

=== RPM installation

You can install `rhoas` as an RPM if you are using Red Hat Enterprise Linux (RHEL), Fedora, or CentOS.

.Procedure

. In a web browser, navigate to the `rhoas` Releases page and choose the version of `rhoas` you would like to install.

. Use `dnf`/`yum` to install the desired version of `rhoas`:
+
--
This example installs `rhoas` version `0.19.0`:

[source,shell]
----
$ sudo dnf install -y https://github.com/bf3fc6c/cli/releases/download/0.19.0/rhoas_0.19.0_linux_amd64.rpm
----
--

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` 0.19.0 is installed:

[source,shell]
----
$ rhoas --version
rhoas version 0.19.0
----
--

== Installing rhoas on macOS

.Procedure

. Review the `install.sh` installation script.
+
The script is located at https://github.com/bf3fc6c/cli/blob/main/scripts/install.sh.

. Run the `install.sh` script:
+
--
[source,shell]
----
$ curl -o- https://raw.githubusercontent.com/bf3fc6c/cli/main/scripts/install.sh | bash
----

[NOTE]
====
You can use the `-s` argument to install a specific version of the `rhoas` CLI. For example, this command installs version `0.19.0`:

[source,shell]
----
$ curl -o- https://raw.githubusercontent.com/bf3fc6c/cli/main/scripts/install.sh | bash -s 0.19.0
----
====

The `rhoas` CLI is installed in `$HOME/bin`.
--

. Verify that the `rhoas` installation directory is on your `$PATH`.
+
--
To check your `$PATH`, run the following command:

[source,shell]
----
$ echo $PATH
----
--

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` 0.19.0 is installed:

[source,shell]
----
$ rhoas --version
rhoas version 0.19.0
----
--

== Installing rhoas on Windows

.Procedure

. Navigate to the `rhoas` link:https://github.com/bf3fc6c/cli/releases[Releases page].

. Download the latest `rhoas` .zip file.

. On your computer, create a `C:\rhoas` folder.

. Extract the `rhoas.exe` file from the .zip file that you downloaded.

. Move the `rhoas.exe` file to `C:\rhoas`.

. If you are using Windows 10, set the `PATH` variable.

.. Click *Search* and type `env` or `environment`.

.. Select *Edit environment variables for your account*.

.. In the *Variable* section, select *Path*, and click *Edit*.

.. Click *New*, and enter `C:\rhoas`.

ifndef::enterprise[]
== Next steps

link:configuring-the-cli.adoc[Configuring the CLI]
endif::[]
