== Using the CLI

Review the following sections to learn how to complete tasks using the CLI.

=== Creating a Kafka instance

Use the `rhoas kafka create` command to create a new Kafka instance.

[source,shell]
----
$ rhoas kafka create --name "my-kafka"
Creating Kafka instance
Created new Kafka instance:
{
    "id": "1lVumk6qWk3ZRQfCssZNNTGvR6Q",
    "kind": "Kafka",
    "href": "/api/managed-services-api/v1/kafkas/1lVumk6qWk3ZRQfCssZNNTGvR6Q",
    "status": "accepted",
    "cloud_provider": "aws",
    "multi_az": true,
    "region": "us-east-1",
    "owner": "developer",
    "name": "my-kafka",
    "created_at": "2020-12-11T13:52:20.216679345Z",
    "updated_at": "2020-12-11T13:52:20.216679345Z"
}
----

NOTE: A Kafka instance will automatically be "used" when created.

=== Viewing the status of your current services

Use the `rhoas status` command to view the status of all current services.

[source,shell]
----
$ rhoas kafka status

  Kafka
  ------------------------------------------------------------------------------------
  ID:                     1nh3qkcXuBGMlbIPDqhNbswIZCB
  Name:                   my-kafka-instance
  Status:                 ready
  Bootstrap URL:          my-kafka-instance--nh-qkcxubgmlbipdqhnbswizcb.kafka.devshift.org:443
----

=== Viewing a list of Kafka instances

To view a list of Kafka instances in your organization use the `rhoas kafka list` command.

[source,shell]
----
$ rhoas kafka list
  ID (2)                        NAME              OWNER      STATUS     CLOUD PROVIDER   REGION     
 ----------------------------- --------------- ------------ ---------- ---------------- ----------- 
  1lVcpo1c9kx6a9rbablGBY8RiD8   my-test-kafka   developer2   complete   aws              us-east-1  
  1lVumk6qWk3ZRQfCssZNNTGvR6Q   my-kafka        developer    complete   aws              us-east-1  
----

=== Describing a Kafka instance

To display all information on-demand about the current Kafka instance, run `rhoas kafka describe`.

[source,shell]
----
$ rhoas kafka describe
{
    "id": "1lVumk6qWk3ZRQfCssZNNTGvR6Q",
    "kind": "Kafka",
    "href": "/api/managed-services-api/v1/kafkas/1lVumk6qWk3ZRQfCssZNNTGvR6Q",
    "status": "accepted",
    "cloud_provider": "aws",
    "multi_az": true,
    "region": "us-east-1",
    "owner": "developer",
    "name": "my-kafka",
    "bootstrapServerHost": "my-kafka--lvumk-qwk-zrqfcssznntgvr-q.apps.ms-bv8dm6nbd3jo.cx74.s1.devshift.org",
    "created_at": "2020-12-11T13:52:20.216679345Z",
    "updated_at": "2020-12-11T13:52:20.216679345Z"
}
----

TIP: You can pass the `--id` flag to describe a different Kafka instance.

=== Using a Kafka instance

The `rhoas kafka use` command can be used to switch the current Kafka instance context.

[source,shell]
----
$ rhoas kafka use --id 1lVcpo1c9kx6a9rbablGBY8RiD8
{
    "id": "1lVcpo1c9kx6a9rbablGBY8RiD8",
    "kind": "Kafka",
    "href": "/api/managed-services-api/v1/kafkas/1lVcpo1c9kx6a9rbablGBY8RiD8",
    "status": "complete",
    "cloud_provider": "aws",
    "multi_az": true,
    "region": "us-east-1",
    "owner": "developer2",
    "name": "my-kafka-instance",
    "bootstrapServerHost": "my-kafka-instance--lvcpo-c-kx-a-rbablgby-rida.apps.ms-bv8dm6nbd3jo.cx74.s1.devshift.org",
    "created_at": "2020-12-11T11:24:44.115583Z",
    "updated_at": "2020-12-11T11:25:05.234173Z"
}
----

=== Creating a Kafka topic

You can create a topic for the current Kafka instance with the `rhoas kafka topics create` command.

[source,shell]
----
$ rhoas kafka topics create --name "my-first-topic"
TODO
----

=== Listing Kafka topics

To list the topics for the current Kafka instance use the `rhoas kafka topics list` command.

[source,shell]
----
$ rhoas kafka topics list
TODO
----

=== Deleting a Kafka topic

The `rhoas kafka delete` command allows you to delete a Kafka topic.

[source,shell]
----
$ rhoas kafka topics delete --name "my-first"
TODO
----

=== Deleting a Kafka instance

To permanently delete the current Kafka instance use the `rhoas kafka delete` command.

[source,shell]
----
$ rhoas kafka delete
? Are you sure you want to delete the Kafka instance my-kafka-instance? Yes
? Confirm the name of the instance you want to permanently delete: my-kafka-instance
Kafka instance my-kafka-instance has successfully been deleted
----

TIP: You can pass the `--id` flag to delete a different Kafka instance.

=== Creating a Service Account

You can use the `rhoas serviceaccount create` command to create a new service account with credentials.
The credentials are exported to a file on your computer and can be used to authenticate your application with managed services.

[source,shell]
----
$ rhoas serviceaccount create --name "my-service-acct" -o json

Service account my-service-account created
Credentials saved to /home/developer/my-project/credentials.yaml
----

Your service account credentials will be saved to a JSON file for use later.

[source,shell]
----
$ cat credentials.json
{ 
	"user":"srvc-acct-eb575691-b94a-41f1-ab97-50ade0cd1094", 
	"password":"facf3df1-3c8d-4253-aa87-8c95ca5e1225" 
}
----

==== Next steps

link:logging-out.adoc[Logging out]