[id="proc-using-rhoas_{context}"]
= Using rhoas

[role="_abstract"]
As a developer of applications and services,
you can use `rhoas` to create Kafka instances and connect your applications and services to these instances.

The following procedures demonstrate a basic workflow to get started quickly:

* xref:_creating_a_kafka_instance[Create a Kafka instance]

* xref:_creating_a_service_account[Create a service account]

* xref:_creating_a_kafka_topic[Create a Kafka topic]

* xref:_commands_for_managing_kafka[Use `rhoas` to manage your Kafka instances, service accounts, and Kafka topics]

== Creating a Kafka instance

A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Kafka instance with default values.
+
--
This example creates a Kafka instance called `my-kafka`.

.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create my-kafka
Kafka instance "my-kafka" created successfully
{
  "cloud_provider": "aws",
  "created_at": "2021-03-17T18:33:50.000799005Z",
  "href": "/api/managed-services-api/v1/kafkas/1ptcsACdx7HVzacKZBA6HRRa1oW",
  "id": "1ptcsACdx7HVzacKZBA6HRRa1oW",
  "kind": "Kafka",
  "multi_az": true,
  "name": "my-kafka",
  "owner": "developer",
  "region": "us-east-1",
  "status": "accepted",
  "updated_at": "2021-03-17T18:33:50.000799005Z"
}
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas kafka create`.
You will be prompted to enter the `Name`, `Cloud Provider`, and `Cloud Region` for the Kafka instance.
====
--

. Enter the following command to verify that the Kafka instance is ready to use.
+
--
This command shows that the Kafka instance is ready to use,
because the `Status` field is `ready`.

.Reviewing details of a Kafka instance
[source,shell]
----
$ rhoas status kafka

  Kafka
  -----------------------------------------------------------------------------------
  ID:                     1ptdfZRHmLKwqW6A3YKM2MawgDh
  Name:                   my-kafka
  Status:                 ready
  Bootstrap URL:          my-kafka--ptdfzrhmlkwqw-a-ykm-mawgdh.kafka.devshift.org:443
----

[NOTE]
====
When you created the Kafka instance, it was set as the current instance automatically.
If you have multiple Kafka instances,
you can switch to a different instance by using the `rhoas kafka use` command.
====
--

== Creating a service account

To connect your applications or services to a Kafka instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You have created a Kafka instance, and it has a `ready` status.

.Procedure

. Enter the following command to create a service account.
+
--
This example creates a service account called `my-service-acct` and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas serviceaccount create --name "my-service-acct" --file-format json

Service account my-service-account created
Credentials saved to /home/developer/my-project/credentials.json
----

Your service account credentials are created and saved to a JSON file.

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas serviceaccount create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Verifying service account credentials
[source,shell]
----
$ cat credentials.json
{
	"user":"srvc-acct-eb575691-b94a-41f1-ab97-50ade0cd1094",
	"password":"facf3df1-3c8d-4253-aa87-8c95ca5e1225"
}
----

You'll use these credentials and the bootstrap server URL to connect your applications and services to your Kafka instance.
--

== Creating a Kafka topic

After creating a Kafka instance, you can create Kafka topics to start producing and consuming messages in your services.

.Prerequisites

* You have created a Kafka instance, and it has a `ready` status.

.Procedure

. Verify that you are using the Kafka instance that you created.
+
--
This example switches to the `my-kafka` instance that was previously created.

.Selecting a Kafka instance to use
[source,shell]
----
$ rhoas kafka use my-kafka
Kafka instance "my-kafka" has been set as the current instance.
----
--

. Create a Kafka topic with default values.
+
--
This example creates the `my-topic` Kafka topic.

.Creating a Kafka topic with default values
[source,shell]
----
$ rhoas kafka topic create my-topic
{
  "config": [
    {
      "key": "retention.ms",
      "value": "-1"
    }
  ],
  "name": "my-topic",
  "partitions": [
    {
      "id": 1,
      "leader": {
        "id": 1
      },
      "replicas": [
        {
          "id": 1
        }
      ]
    }
  ]
}
----

[NOTE]
====
If you do not want to use the default values,
you can specify the number of partitions (`--partitions`) and message retention time (`--retention-ms`).
For more information, see the `rhoas kafka topic create` help.
====
--

. If necessary, you can edit or delete the topic by using the `rhoas kafka topic update` and `rhoas kafka topic delete` commands.

== Commands for managing Kafka

The following list shows the `rhoas` commands you can use to manage your Kafka instances, service accounts, and topics.
For more information about any of the commands,
view the command help (for example, `rhoas kafka list -h`).

* View a list of all Kafka instances in your organization:
+
`rhoas kafka list`

* View configuration details for a particular Kafka instance:
+
`rhoas kafka describe`

* Switch to a different Kafka instance:
+
`rhoas kafka use`

* Delete a Kafka instance:
+
`rhoas kafka delete`

* View a list of Kafka topics:
+
`rhoas kafka topic list`

* View configuration details for a particular Kafka topic:
+
`rhoas kafka topic describe`

* Update the message retention time for a Kafka topic:
+
`rhoas kafka topic update`

* Delete a Kafka topic:
+
`rhoas kafka topic delete`

* View a list of service accounts in your organization:
+
`rhoas serviceaccount list`

* View configuration details for a particular service account:
+
`rhoas serviceaccount describe`

* Generate a new password for a service account:
+
`rhoas serviceaccount reset-credentials`

* Delete a service account:
+
`rhoas serviceaccount delete`

ifndef::enterprise[]
== Next steps

link:logging-out.adoc[Logging out]
endif::[]
