module.exports = {
  rhmas: {
    "Getting Started": ["introduction", "commands"],
    Features: ["placeholder"],
    Commands: [
      "commands/rhmas_auth_autorization",
      "commands/rhmas_auth",
      "commands/rhmas_completion",
      "commands/rhmas_kafka_create",
      "commands/rhmas_kafka_credentials",
      "commands/rhmas_kafka_delete",
      "commands/rhmas_kafka_get",
      "commands/rhmas_kafka_list",
      "commands/rhmas_kafka_status",
      "commands/rhmas_kafka_topics_create",
      "commands/rhmas_kafka_topics_delete",
      "commands/rhmas_kafka_topics_list",
      "commands/rhmas_kafka_topics_update",
      "commands/rhmas_kafka_topics",
      "commands/rhmas_kafka_use",
      "commands/rhmas_kafka",
      "commands/rhmas_login",
      "commands/rhmas_logout",
      "commands/rhmas",
    ],
    Reference: ["architecture", "sdkref"],
  },
};
