/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package managedservices

// ServiceAccountRequestAllOf struct for ServiceAccountRequestAllOf
type ServiceAccountRequestAllOf struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
