name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGER_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign triaged issues to app-services project
      # 1.3.1
      uses: srggrs/assign-one-project-github-action@4fc2b23bdaaac08e64dcc590a6e138d2f9b8c86e
      if: |
        contains(github.event.issue.labels.*.name, 'triage/accepted')
      with:
        project: 'https://github.com/orgs/redhat-developer/projects/3'
        column_name: 'To do'
