name: Generate a CHANGELOG
on: 
  push:
    branches:
      - changelog
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: craicoverflow/install-git-chglog@v0.3.0
        run: git-chglog