name: Validate
on: [pull_request]

jobs:
  validate_comments:
    name: 'Validate Conventional Commits'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # v4
      - uses: wagoid/commitlint-github-action@3d28780bbf0365e29b144e272b2121204d5be5f3