name: Go Build

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - '**.toml'
      - 'go.mod'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - '**.toml'
      - 'go.mod'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          # skip-go-installation: true
          # skip-pkg-cache: true
          # skip-build-cache: true
          args: --timeout 3m0s --verbose
      - name: Check documentation
        run: make check-docs
      - name: Check i18n
        run: make lint-lang
      - name: Check vendoring
        run: make check-vendor
      - name: Build
        run: make binary
      - name: Unit tests
        run: make test
