name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --timeout 2m0s
          # args: --issues-exit-code=0
      - name: Check documentation
        run: make docs/check
      - name: Build
        run: make binary
      - name: Unit tests
        run: make test/unit
      - name: Integration tests
        run: make test/integration
