package generate

import (
	"github.com/MakeNowJust/heredoc"
	"github.com/redhat-developer/app-services-cli/pkg/cmd/registry/registrycmdutil"
)

var (
	templateEnv = heredoc.Doc(`
		## Generated by rhoas cli
		{{if .KafkaHost}}## Kafka Configuration
		KAFKA_HOST={{.KafkaHost}}
		{{end}}{{if .RegistryURL}}## Service Registry Configuration
		SERVICE_REGISTRY_URL={{.RegistryURL}}
		SERVICE_REGISTRY_CORE_PATH=` + registrycmdutil.REGISTRY_CORE_PATH + `
		SERVICE_REGISTRY_COMPAT_PATH=` + registrycmdutil.REGISTRY_COMPAT_PATH + `
		{{end}}
`)

	templateJSON = heredoc.Doc(`
		{
			{{if .KafkaHost}}"kafkaHost":"{{.KafkaHost}}",
			{{end}}{{if .RegistryURL}}"serviceRegistryUrl":"{{.RegistryURL}}",
			"serviceRegistryCorePath":"` + registrycmdutil.REGISTRY_CORE_PATH + `",
			"serviceRegistryCompatPath":"` + registrycmdutil.REGISTRY_COMPAT_PATH + `"{{end}}
		}
	`)

	templateProperties = heredoc.Doc(`
		## Generated by rhoas cli
		{{if .KafkaHost}}## Kafka Configuration
		kafkaHost={{.KafkaHost}} 
		{{end}}{{if .RegistryURL}}## Service Registry Configuration
		serviceRegistryUrl={{.RegistryURL}}
		serviceRegistryCorePath=` + registrycmdutil.REGISTRY_CORE_PATH + `
		serviceRegistryCompatPath=` + registrycmdutil.REGISTRY_COMPAT_PATH + `{{end}}
	`)

	templateConfigMap = heredoc.Doc(`
		apiVersion: v1
		kind: ConfigMap
		metadata:
    name: {{.Name}}
		data:
		  {{if .KafkaHost}}## Kafka Configuration
		  kafka_host: {{.KafkaHost}}
		  {{end}}
		  {{if .RegistryURL}}## Service Registry Configuration
		  service_registry_url: {{.RegistryURL}}
		  service_registry_compat_path: ` + registrycmdutil.REGISTRY_COMPAT_PATH + `
		  service_registry_core_path: ` + registrycmdutil.REGISTRY_CORE_PATH + `{{end}}
	`)
)
