package generate

import (
	"github.com/MakeNowJust/heredoc"
)

var (
	templateEnv = heredoc.Doc(`
		## Generated by rhoas generate-config
		{{if .KafkaURL}}KAFKA_URL={{.KafkaURL}} 
		{{end}}{{if .RegistryURL}}SERVICE_REGISTRY_URL={{.RegistryURL}}
		{{end}}RHOAS_CLIENT_ID={{.ClientID}}
		RHOAS_CLIENT_SECRET={{.ClientSecret}}
		RHOAS_OAUTH_TOKEN_URL={{.TokenURL}}
`)

	templateJSON = heredoc.Doc(`
		{	
			{{if .KafkaURL}}"kafkaUrl":"{{.KafkaURL}}",
			{{end}}{{if .RegistryURL}}"serviceRegistryUrl":"{{.RegistryURL}}",
			{{end}}"rhoasClientID":"{{.ClientID}}",
			"rhoasClientSecret":"{{.ClientSecret}}",
			"rhoasOauthTokenUrl":"{{.TokenURL}}"
		}
	`)

	templateProperties = heredoc.Doc(`
		## Generated by rhoas generate-config
		{{if .KafkaURL}}kafkaUrl={{.KafkaURL}}
		{{end}}{{if .RegistryURL}}serviceRegistryUrl={{.RegistryURL}}
		{{end}}rhoasClientID={{.ClientID}}
		rhoasClientSecret={{.ClientSecret}}
		rhoasOauthTokenUrl={{.TokenURL}}
	`)
)
